import translations from '../../localization/config/translationHelper';

const enum WATER_HEATER_TIMER_VALUES {
  ALWAYS_ON = 0,
  THIRTY_MINUTES = 1850,
  ONE_HOUR = 3650,
  TWO_HOURS = 7250,
  THREE_HOURS = 10850,
  FOUR_HOURS = 14450,
  FIVE_HOURS = 18500,
  SIX_HOURS = 21650,
  SEVEN_HOURS = 25250,
  EIGHT_HOURS = 28850,
  NINE_HOURS = 32450,
  TEN_HOURS = 36500,
  ELEVEN_HOURS = 39650,
  TWELVE_HOURS = 43250,
  THERTEEN_HOURS = 46850,
  FORTEEN_HOURS = 50450,
  FIFTEEN_HOURS = 54500,
  SIXTEEN_HOURS = 57650,
  SEVENTEEN_HOURS = 61250,
  EIGHTEEN_HOURS = 64850,
  NINTYN_HOURS = 68450,
  TWENTY_HOURS = 72500,
  TWENTY_ONE_HOURS = 75650,
  TWENTY_TWO_HOURS = 79250,
  TWENTY_THREE_HOURS = 82850,
  TWENTY_FOUR_HOURS = 86450,
}

const WATER_HEATER_TIMERS_OPTIONS = [
  {
    label: translations.fullClimate.waterHeater.alwaysOn,
    value: WATER_HEATER_TIMER_VALUES.ALWAYS_ON,
  },
  {
    value: WATER_HEATER_TIMER_VALUES.THIRTY_MINUTES,
  },
  {
    value: WATER_HEATER_TIMER_VALUES.ONE_HOUR,
  },
  {
    value: WATER_HEATER_TIMER_VALUES.TWO_HOURS,
  },
  {
    value: WATER_HEATER_TIMER_VALUES.THREE_HOURS,
  },
  {
    value: WATER_HEATER_TIMER_VALUES.FOUR_HOURS,
  },
  {
    value: WATER_HEATER_TIMER_VALUES.FIVE_HOURS,
  },
  {
    value: WATER_HEATER_TIMER_VALUES.SIX_HOURS,
  },
  {
    value: WATER_HEATER_TIMER_VALUES.SEVEN_HOURS,
  },
  {
    value: WATER_HEATER_TIMER_VALUES.EIGHT_HOURS,
  },
  {
    value: WATER_HEATER_TIMER_VALUES.NINE_HOURS,
  },
  {
    value: WATER_HEATER_TIMER_VALUES.TEN_HOURS,
  },
  {
    value: WATER_HEATER_TIMER_VALUES.ELEVEN_HOURS,
  },
  {
    value: WATER_HEATER_TIMER_VALUES.TWELVE_HOURS,
  },
  {
    value: WATER_HEATER_TIMER_VALUES.THERTEEN_HOURS,
  },
  {
    value: WATER_HEATER_TIMER_VALUES.FORTEEN_HOURS,
  },
  {
    value: WATER_HEATER_TIMER_VALUES.FIFTEEN_HOURS,
  },
  {
    value: WATER_HEATER_TIMER_VALUES.SIXTEEN_HOURS,
  },
  {
    value: WATER_HEATER_TIMER_VALUES.SEVENTEEN_HOURS,
  },
  {
    value: WATER_HEATER_TIMER_VALUES.EIGHTEEN_HOURS,
  },
  {
    value: WATER_HEATER_TIMER_VALUES.NINTYN_HOURS,
  },
  {
    value: WATER_HEATER_TIMER_VALUES.TWENTY_HOURS,
  },
  {
    value: WATER_HEATER_TIMER_VALUES.TWENTY_ONE_HOURS,
  },
  {
    value: WATER_HEATER_TIMER_VALUES.TWENTY_TWO_HOURS,
  },
  {
    value: WATER_HEATER_TIMER_VALUES.TWENTY_THREE_HOURS,
  },
  {
    value: WATER_HEATER_TIMER_VALUES.TWENTY_FOUR_HOURS,
  },
];

export {WATER_HEATER_TIMERS_OPTIONS};
