interface Dark {
  THEME_accent_primary_regular_value: '{color.GRAY.30}';
  THEME_accent_primary_variation_1_value: '{color.GRAY.300}';
  THEME_accent_primary_variation_2_value: '{color.GRAY.800}';
  THEME_accent_secondary_regular_value: '{color.BLUE.500}';
  THEME_accent_secondary_variation_1_value: '{color.BLUE.300}';
  THEME_accent_secondary_variation_2_value: '{color.BLUE.900}';
  THEME_accent_tertiary_regular_value: '{color.SPROUT.500}';
  THEME_accent_tertiary_variation_1_value: '{color.SPROUT.300}';
  THEME_accent_tertiary_variation_2_value: '{color.SPROUT.900}';
  THEME_layout_background_value: '{color.GRAY.900}';
  THEME_layout_surface_value: '{color.GRAY.800}';
  THEME_layout_divider_value: '{color.GRAY.700}';
  THEME_layout_spot_value: '{color.GLOW.600}';
  THEME_layout_disabled_value: '{color.GRAY.700}';
  THEME_layout_navbar_value: '{color.GRAY.800}';
  THEME_text_regular_value: '{color.White}';
  THEME_text_regular_disabled_value: '{color.GRAY.700}';
  THEME_text_inverted_value: '{color.GRAY.800}';
  THEME_text_inverted_disabled_value: '{color.GRAY.100}';
  THEME_text_neutral_value: '{color.GRAY.400}';
  THEME_text_light_value: '{color.White}';
  THEME_text_dark_value: '{color.GRAY.900}';
  THEME_semantic_negative_regular_value: '{color.RED.500}';
  THEME_semantic_negative_dark_value: '{color.RED.900}';
  THEME_semantic_positive_regular_value: '{color.GREEN.500}';
  THEME_semantic_positive_dark_value: '{color.GREEN.900}';
  THEME_semantic_attention_regular_value: '{color.YELLOW.500}';
  THEME_semantic_attention_dark_value: '{color.YELLOW.900}';
  THEME_semantic_warm_regular_value: '{color.RED.600}';
  THEME_semantic_warm_dark_value: '{color.RED.900}';
  THEME_semantic_cold_regular_value: '{color.BLUE.500}';
  THEME_semantic_cold_dark_value: '{color.BLUE.900}';
  THEME_semantic_neutral_regular_value: '{color.GRAY.400}';
  THEME_semantic_neutral_dark_value: '{color.GRAY.700}';
}
declare const Dark: Dark;
export = Dark;
