const NUMBER_OF_LINES = 2;
const SPACER_SIZE = 20;
const BUTTON_HEIGHT = 40;
const BORDER_WIDTH = 0.5;
const BOTTOM_SHEET_HEIGHT = 450;
const BORDER_RADIUS = 16;

export {
  NUMBER_OF_LINES,
  SPACER_SIZE,
  BUTTON_HEIGHT,
  BORDER_WIDTH,
  BOTTOM_SHEET_HEIGHT,
  BORDER_RADIUS,
};
