const elementIdConstants = {
  TestId: {
    DeviceManagementDetailsScreen:
      'com.dometicapp:id/DeviceManagementDetailsScreen',
    DeviceManagementScreen: 'com.dometicapp:id/DeviceManagementScreen',
    CheckUpdatesScreen: 'com.dometicapp:id/CheckUpdatesScreen',
    NotificationScreen: 'com.dometicapp:id/NotificationScreen',
    DeviceNotificationScreen: 'com.dometicapp:id/DeviceNotificationScreen',
    SDBHomeScreen: 'com.dometicapp:id/SDBHomeScreen',
    SDBSettingsScreen: 'com.dometicapp:id/SDBSettingsScreen',
    GuestListPinScreen: 'com.dometicapp:id/GuestListPinScreen',
    EditGuestListPinScreen: 'com.dometicapp:id/EditGuestListPinScreen',
    EditGuestPinScreen: 'com.dometicapp:id/EditGuestPinScreen',
    MasterPinScreen: 'com.dometicapp:id/MasterPinScreen',
    // Sensor UI related ElementID constants
    MainDoorScreen: 'com.dometicapp:id/MainDoorScreen',
    ClimateSensorScreen: 'com.dometicapp:id/ClimateSensorScreen',
    DometicLPGTankSensorScreen: 'com.dometicapp:id/DometicLPGTankSensorScreen',
    BackWindowScreen: 'com.dometicapp:id/BackWindowScreen',
    SensorOnBoardingDeviceDetails:
      'com.dometicapp:id/SensorOnBoardingDeviceDetails',
  },
  Login: {
    // Element id constants for Login screen
    container: 'com.dometicapp:id/login-container',
    backgroundImage: 'com.dometicapp:id/login-backgroundImage',
    spinner: 'com.dometicapp:id/login-spinner',
    welcomeText: 'com.dometicapp:id/login-welcomeText',
    loginText: 'com.dometicapp:id/login-loginText',
    email: 'com.dometicapp:id/login-email',
    password: 'com.dometicapp:id/login-password',
    invalidEmailText: 'com.dometicapp:id/login-invalidEmail-message',
    securePwd: 'com.dometicapp:id/login-securePwd',
    securePwdField: 'com.dometicapp:id/login-securePwdfield',
    invalidsecurePwdText: 'com.dometicapp:id/login-invalidsecurePwd-message',
    goToForgot: 'com.dometicapp:id/login-goToForgot',
    goToForgotText: 'com.dometicapp:id/login-forgotText',
    noAccountText: 'com.dometicapp:id/login-noAccountText',
    goToSignUp: 'com.dometicapp:id/login-goToSignUp',
    goToSignUpText: 'com.dometicapp:id/login-signUpText',
    loginButton: 'com.dometicapp:id/login-loginButton',
    loginButtonText: 'com.dometicapp:id/login-loginButtonText',
    facebookIconContainer: 'com.dometicapp:id/login-facebookIconContainer',
    googleIconContainer: 'com.dometicapp:id/login-googleIconContainer',
    twitterIconContainer: 'com.dometicapp:id/login-twitterIconContainer',
    facebookIcon: 'com.dometicapp:id/login-facebookIcon',
    googleIcon: 'com.dometicapp:id/login-googleIcon',
    twitterIcon: 'com.dometicapp:id/login-twitterIcon',
    useAccount: 'com.dometicapp:id/login-useAccount',
  },
  ResetPwdScreen: {
    background: 'com.dometicapp:id/resetPwd-background',
  },
  MapComponent: {
    background: 'com.dometicapp:id/mapComponent-background',
  },
  ManualNetworkScreen: {
    background: 'com.dometicapp:id/ManualNetworkScreen-background',
  },
  AutoNetworkScreen: {
    background: 'com.dometicapp:id/AutoNetworkScreen-background',
  },
  WifiNetworkHelpScreen: {
    background: 'com.dometicapp:id/WifiNetworkHelpScreen-background',
  },
  SetupWifiScreen: {
    background: 'com.dometicapp:id/SetupWifiScreen-background',
  },
  SensorOnBoardingScreen: {
    background: 'com.dometicapp:id/SensorOnBoardingScreen-background',
  },
  MiniBarControlScreen: {
    background: 'com.dometicapp:id/MainMiniBarControlScreen-background',
  },
  GatewayQrCode: {
    background: 'com.dometicapp:id/GatewayQrCode-background',
  },
  SignUp: {
    // Element id constants for Signup screen
    container: 'com.dometicapp:id/signUp-container',
    backgroundImage: 'com.dometicapp:id/signUp-backgroundImage',
    spinner: 'com.dometicapp:id/signUp-spinner',
    createAccount: 'com.dometicapp:id/signUp-createAccount',
    emailLabel: 'com.dometicapp:id/signUp-email',
    emailTextField: 'com.dometicapp:id/signUp-emailField',
    invalidEmailText: 'com.dometicapp:id/signUp-invalidemail-message',
    securePwdLabel: 'com.dometicapp:id/signUp-securePwdLabel',
    securePwdField: 'com.dometicapp:id/signUp-securePwdField',
    invalidSecurePwdText: 'com.dometicapp:id/signUp-invalidSecurePwd-message',
    togglePassword: 'com.dometicapp:id/signUp-toggleShowPassword',
    viewPasswordImage: 'com.dometicapp:id/signUp-viewPassword',
    tooltip: 'com.dometicapp:id/signUp-tooltip',
    validPasswordTick: 'validPwd-tick',
    invalidPasswordTick: 'invalidPwd-tick',
    icon: 'icon',
    exampleSecurePwd: 'exampleSecurePwd',
    tooltipContent: 'tooltipContent',
    toolTipcontainer: 'container',
    verifySecurePwdLabel: 'com.dometicapp:id/signUp-verify',
    verifySecurePwdField: 'com.dometicapp:id/signUp-verifySecurePwd',
    invalidShowVerifyText: 'com.dometicapp:id/signUp-showVerifyPasswordError',
    dometicMarketing: 'com.dometicapp:id/signUp-dometicMarketingContainer',
    dometicMarketingText: 'com.dometicapp:id/signUp-dometicMarketingText',
    goToEula: 'com.dometicapp:id/signUp-goToEula',
    checkBox: 'com.dometicapp:id/signUp-checkBoxMarketingButton',
    isChecked: 'com.dometicapp:id/signUp-isCheckedMarketing',
    checkBoxOffer: 'com.dometicapp:id/signUp-checkBoxOfferButton',
    isCheckedOffer: 'com.dometicapp:id/signUp-isCheckedOffer',
    showOffersContainer: 'com.dometicapp:id/signUp-offerContainer',
    showOffersText: 'com.dometicapp:id/signUp-showOffers',
    showText: 'com.dometicapp:id/signUp-showText',
    moreDataText: 'com.dometicapp:id/signUp-moreData',
    signUpButton: 'com.dometicapp:id/signUp-signUpButton',
    haveAccountText: 'com.dometicapp:id/signUp-haveAccount',
    navigateToLogin: 'com.dometicapp:id/signUp-navigateToLogin',
    overlayContainer: 'com.dometicapp:id/signUp-overlaycontainer',
    closeButton: 'com.dometicapp:id/signUp-closeButton',
    awesomeText: 'com.dometicapp:id/signUp-awesome',
    userAccount: 'com.dometicapp:id/signUp-userAccount',
    verifyLoginText: 'com.dometicapp:id/signUp-verifyAndLogin',
    noEmailText: 'com.dometicapp:id/signUp-noEmail',
    clickText: 'com.dometicapp:id/signUp-click',
    clickHereContainer: 'com.dometicapp:id/signUp-clickHereContainer',
    clickHereText: 'com.dometicapp:id/signUp-clickHere',
    resendLabel: 'com.dometicapp:id/signUp-resend',
    verifyEmail: 'com.dometicapp:id/signUp-verifyEmail',
    verifySecurePwdInvalid: 'com.dometicapp:id/signUp-verifyPwdInvalid',
    verifySecurePwdIcon: 'securePwdInfoIcon',
    userNameInvalid: 'userNameInvalid',
    signUpText: 'com.dometicapp:id/signUp-signUpText',
    loginText: 'com.dometicapp:id/signUp-loginText',
  },
  ForgotPwd: {
    // Element id constants for Forgot password screen
    container: 'com.dometicapp:id/forgot-container',
    backgroundImage: 'com.dometicapp:id/forgot-backgroundImage',
    spinner: 'com.dometicapp:id/forgot-spinner',
    backToLogin: 'com.dometicapp:id/forgot-backToLogin',
    backToLoginImage: 'com.dometicapp:id/forgot-backToLoginImage',
    forgotPwdText: 'com.dometicapp:id/forgot-forgotPwdText',
    enterEmailLabel: 'com.dometicapp:id/forgot-enterEmail',
    createPassText: 'com.dometicapp:id/forgot-createPass',
    emailReceive: 'com.dometicapp:id/forgot-emailReceive',
    checkSpam: 'com.dometicapp:id/forgot-checkSpam',
    checkInbox: 'com.dometicapp:id/forgot-checkInbox',
    checkinMin: 'com.dometicapp:id/forgot-checkinMin',
    emailLabel: 'com.dometicapp:id/forgot-email',
    emailTextFeild: 'com.dometicapp:id/forgot-emailTextfield',
    invalidEmailText: 'com.dometicapp:id/forgot-invalidEmail-message',
    sendButton: 'com.dometicapp:id/forgot-sendButton',
    sendButtonText: 'com.dometicapp:id/forgot-sendPasswordText',
  },
  DeveloperPanel: {
    // Element id constants for DeveloperPanel screen
    container: 'com.dometicapp:id/devPanel-container',
    backgroundImage: 'com.dometicapp:id/devPanel-backgroundImage',
    spinner: 'com.dometicapp:id/devPanel-spinner',
    backToLoginImage: 'com.dometicapp:id/devPanel-backToLoginImage',
    backToLogin: 'com.dometicapp:id/devPanel-backToLogin',
    titleText: 'com.dometicapp:id/devPanel-titleText',
    devPanelListContainer: 'com.dometicapp:id/devPanel-ListContainer',
    devPanelContainerItem: 'com.dometicapp:id/devPanel-ListContainerItem',
    productionEnvironmentContainer:
      'com.dometicapp:id/devPanel-productionEnvironmentContainer',
    devlopmentEnvironmentContainer:
      'com.dometicapp:id/devPanel-developmentEnvironmentContainer',
    multipleBleContainer: 'com.dometicapp:id/devPanel-multipleBleContainer',
    applyButton: 'com.dometicapp:id/devPanel-applyButton',
    applyButtonText: 'com.dometicapp:id/devPanel-applyButtonnText',
  },
  Gateway: {
    // Element id constants for Gateway screen
    container: 'com.dometicapp:id/gateway-container',
    backgroundImage: 'com.dometicapp:id/gateway-backgroundImage',
    spinner: 'com.dometicapp:id/gateway-spinner',
    backToServiceGallery: 'com.dometicapp:id/gateway-backButton',
    backButtonImage: 'com.dometicapp:id/gateway-backButtonImage',
    gatewayText: 'com.dometicapp:id/gateway-enterGatewayText',
    serialNumberText: 'com.dometicapp:id/gateway-serialnumberText',
    serialNumberField: 'com.dometicapp:id/gateway-serialNumberField',
    serialFormat: 'com.dometicapp:id/gateway-serialFormat',
    invalidSerialNumberText:
      'com.dometicapp:id/gateway-invalidSerialNumber-message',
    connectButton: 'com.dometicapp:id/gateway-connectButton',
    connectText: 'com.dometicapp:id/gateway-connectText',
    orText: 'com.dometicapp:id/gateway-orText',
    navigateToScan: 'com.dometicapp:id/gateway-navigateToScan',
    qrIcon: 'com.dometicapp:id/gateway-qrIcon',
    scanText: 'com.dometicapp:id/gateway-scanText',
  },
  QRCode: {
    // Element id constants for QRCode screen
    container: 'com.dometicapp:id/qrCode-container',
    backgroundImage: 'com.dometicapp:id/qrCode-backgroundImage',
    spinner: 'com.dometicapp:id/qrCode-spinner',
    backButtonContainer: 'com.dometicapp:id/qrCode-backButton',
    backButtonImage: 'com.dometicapp:id/qrCode-backButtonImage',
    scanQr: 'com.dometicapp:id/qrCode-scanQr',
    moveCamera: 'com.dometicapp:id/qrCode-moveCamera',
    deviceQr: 'com.dometicapp:id/qrCode-deviceQr',
    cameraImage: 'com.dometicapp:id/qrCode-cameraImage',
    scanningCode: 'com.dometicapp:id/qrCode-scanningCode',
    scannerContainer: 'com.dometicapp:id/qrCode-QRCodeScanner',
    permissionDeniedContainer:
      'com.dometicapp:id/qrCode-permissionDeniedContainer',
    permissionDenied: 'com.dometicapp:id/qrCode-permissionDenied',
  },
  ResendScreen: {
    // Element id constants for Resend screen
    container: 'com.dometicapp:id/resend-container',
    backgroundImage: 'com.dometicapp:id/resend-backgroundImage',
    spinner: 'com.dometicapp:id/resend-spinner',
    backButtonContainer: 'com.dometicapp:id/resend-backButtonContainer',
    backButtonImage: 'com.dometicapp:id/resend-backButtonImage',
    resendLabel: 'com.dometicapp:id/resend-resend',
    verificationLabel: 'com.dometicapp:id/resend-verification',
    emailLabel: 'com.dometicapp:id/resend-email',
    emailField: 'com.dometicapp:id/resend-emailField',
    inavlidEmailMessage: 'com.dometicapp:id/resend-invalidemail-message',
    sendButton: 'com.dometicapp:id/resend-sendButton',
    sendButtonText: 'com.dometicapp:id/resend-sendButtonText',
  },
  ScanBLE: {
    // Element id constants for ScanBLE component
    backgroundImage: 'com.dometicapp:id/scanBle-backgroundImage',
    container: 'com.dometicapp:id/scanBle-container',
    brandLogo: 'com.dometicapp:id/scanBle-brandLogo',
    activityIndicator: 'com.dometicapp:id/scanBle-activityIndicator',
    searchText: 'com.dometicapp:id/scanBle-searchText',
    headerBLE: 'com.dometicapp:id/scanBle-headerBle',
    deviceDatacontainer: 'com.dometicapp:id/scanBle-deviceDatacontainer',
    wifiDeviceImage: 'com.dometicapp:id/scanBle-wifiDeviceImage',
    bleDeviceImage: 'com.dometicapp:id/scanBle-bleDeviceImage',
    deviceName: 'com.dometicapp:id/scanBle-deviceName',
    noDevice: 'com.dometicapp:id/scanBle-noDevice',
    noDeviceMessage: 'com.dometicapp:id/scanBle-noDeviceMessage',
    clearStartScreenTimer: 'com.dometicapp:id/scanBle-clearStartScreenTimer',
    tryScanning: 'com.dometicapp:id/scanBle-tryScanning',
    addImageContainer: 'com.dometicapp:id/scanBle-addImageContainer',
    iconAddProduct: 'com.dometicapp:id/scanBle-iconAddProduct',
    addProductText: 'com.dometicapp:id/scanBle-addProduct',
    loader: 'com.dometicapp:id/scanBle-loader',
  },
  Dashboard: {
    // Element id constants for ScanBLE component
    backgroundImage: 'com.dometicapp:id/Dashboard-backgroundImage',
    container: 'com.dometicapp:id/Dashboard-container',
    activityIndicatorContainer:
      'com.dometicapp:id/Dashboard-activityIndicatorContainer',
    activityIndicator: 'com.dometicapp:id/Dashboard-activityIndicator',
    searchText: 'com.dometicapp:id/Dashboard-searchText',
    header: 'com.dometicapp:id/Dashboard-header',
    list: 'com.dometicapp:id/Dashboard-list',
    outerCard: 'com.dometicapp:id/Dashboard-outerCard',
    card: 'com.dometicapp:id/Dashboard-card',
    cardImage: 'com.dometicapp:id/Dashboard-cardImage',
    cardText: 'com.dometicapp:id/Dashboard-cardText',
  },
  DeviceManagement: {
    // Element id constants for ScanBLE component
    backgroundImage: 'com.dometicapp:id/DeviceManagement-backgroundImage',
    header: 'com.dometicapp:id/DeviceManagement-header',
    list: 'com.dometicapp:id/DeviceManagement-list',
    addNewButton: 'com.dometicapp:id/DeviceManagement-addNewButton',
    addNewButtonText: 'com.dometicapp:id/DeviceManagement-addNewButtonText',
    itemContainer: 'com.dometicapp:id/DeviceManagement-itemContainer',
    smallLogo: 'com.dometicapp:id/DeviceManagement-smallLogo',
    deviceName: 'com.dometicapp:id/DeviceManagement-deviceName',
    rightIcon: 'com.dometicapp:id/DeviceManagement-rightIcon',
  },
  OnBoarding: {
    // Element id constants for ScanBLE component
    backgroundImage: 'com.dometicapp:id/onBoarding-backgroundImage',
    container: 'com.dometicapp:id/onBoarding-container',
    activityIndicatorContainer:
      'com.dometicapp:id/onBoarding-activityIndicatorContainer',
    activityIndicator: 'com.dometicapp:id/onBoarding-activityIndicator',
    searchText: 'com.dometicapp:id/onBoarding-searchText',
    header: 'com.dometicapp:id/onBoarding-header',
    errorContainer: 'com.dometicapp:id/onBoarding-errorContainer',
    noDeviceTitle: 'com.dometicapp:id/onBoarding-noDeviceTitle',
    attentionImage: 'com.dometicapp:id/onBoarding-attentionImage',
    closeImage: 'com.dometicapp:id/onBoarding-closeImage',
    backImage: 'com.dometicapp:id/onBoarding-backImage',
    bleMsgText: 'com.dometicapp:id/onBoarding-bleMsgText',
    deviceFoundTitle: 'com.dometicapp:id/onBoarding-deviceFoundTitle',
    selectDeviceText: 'com.dometicapp:id/onBoarding-selectDeviceText',
    rightImage: 'com.dometicapp:id/onBoarding-rightImage',
    deviceDatacontainer: 'com.dometicapp:id/onBoarding-deviceDatacontainer',
    deviceName: 'com.dometicapp:id/onBoarding-deviceName',
    macAddress: 'com.dometicapp:id/onBoarding-macAddress',
    selectedDeviceName: 'com.dometicapp:id/onBoarding-selectedDeviceName',
    nameTitle: 'com.dometicapp:id/onBoarding-nameTitle',
    nameInput: 'com.dometicapp:id/onBoarding-nameInput',
    nextButton: 'com.dometicapp:id/onBoarding-nextButton',
    nextButtonText: 'com.dometicapp:id/onBoarding-nextButtonText',
    searchAgainButton: 'com.dometicapp:id/onBoarding-searchAgainButton',
    searchAgainButtonText: 'com.dometicapp:id/onBoarding-searchAgainButtonText',
    resultMainContainer: 'com.dometicapp:id/onBoarding-resultMainContainer',
    resultContentContainer:
      'com.dometicapp:id/onBoarding-resultContentContainer',
    resultText: 'com.dometicapp:id/onBoarding-resultText',
    hintText: 'com.dometicapp:id/onBoarding-hintText',
    resultButton: 'com.dometicapp:id/onBoarding-resultButton',
    resultButtonText: 'com.dometicapp:id/onBoarding-resultButtonText',
    bleInstructionBtn: 'com.dometicapp:id/onBoarding-bleInstructionBtn',
    bleInstructionContainer:
      'com.dometicapp:id/onBoarding-bleInstructionContainer',
  },
  BrandSelection: {
    // Element id constants for BrandSelection screen
    backgroundImage: 'com.dometicapp:id/brandSelection-backGroundImage',
    spinner: 'com.dometicapp:id/brandSelection-spinner',
    backButtonContainer: 'com.dometicapp:id/brandSelection-backButtonContainer',
    backButtonImage: 'com.dometicapp:id/brandSelection-backButtonImage',
    selectBrandText: 'com.dometicapp:id/brandSelection-selectBrandText',
    lmcLogoContainer: 'com.dometicapp:id/brandSelection-lmcLogoContainer',
    lmcLogo: 'com.dometicapp:id/brandSelection-lmcLogo',
    orText: 'com.dometicapp:id/brandSelection-orText',
    eribaLogoContainer: 'com.dometicapp:id/brandSelection-eribaLogoContainer',
    eribaLogo: 'com.dometicapp:id/brandSelection-eribaLogo',
  },
  Climate: {
    // Element id constants for Climate screen
    backgroundImage: 'com.dometicapp:id/climate-backgroundImage',
    container: 'com.dometicapp:id/climate-container',
    insideTemp: 'com.dometicapp:id/climate-insideTemp',
    insideTempValue: 'com.dometicapp:id/climate-insideTempValue',
    insideTempUnit: 'com.dometicapp:id/climate-insideTempUnit',
    outsideTemp: 'com.dometicapp:id/climate-outsideTemp',
    outsideTempValue: 'com.dometicapp:id/climate-outsideTempValue',
    outsideTempUnit: 'com.dometicapp:id/climate-outsideTempUnit',
    fanIcon: 'com.dometicapp:id/climate-fanIcon',
    fanSpeed: 'com.dometicapp:id/climate-FanSpeed',
    applyChangesText: 'com.dometicapp:id/climate-applyChangesText',
    applyTempButton: 'com.dometicapp:id/climate-applyTemperature',
    applyText: 'com.dometicapp:id/climate-applyText',
    scrollView: 'com.dometicapp:id/climate-scrollView',
    powerContainer: 'com.dometicapp:id/climate-powerContainer',
    powerText: 'com.dometicapp:id/climate-powerText',
    powerToggle: 'com.dometicapp:id/climate-powerToggle',
    powerToggleStatus: 'com.dometicapp:id/climate-powerToggleStatus',
    temperatureContainer: 'com.dometicapp:id/climate-temperatureContainer',
    temperatureText: 'com.dometicapp:id/climate-temperature',
    temperatureValue: 'com.dometicapp:id/climate-temperatureValue',
    selectedClimate: 'com.dometicapp:id/climate-selectedClimate',
    selectedClimateContainer:
      'com.dometicapp:id/climate-selectedClimateContainer',
    temperatureArray: 'com.dometicapp:id/climate-temperatureArray',
    temperatureArrayValue: 'com.dometicapp:id/climate-temperatureArrayValue',
    tempValue: 'com.dometicapp:id/climate-tempValue',
    waterLevelContainer: 'com.dometicapp:id/climate-waterLevelContainer',
    waterLevelText: 'com.dometicapp:id/climate-waterLevelText',
    selectedWaterLevel: 'com.dometicapp:id/climate-selectedWaterLevel',
    waterLevelCollapse: 'com.dometicapp:id/climate-waterLeveliconCollapse',
    energyContainer: 'com.dometicapp:id/climate-energyContainer',
    energyText: 'com.dometicapp:id/climate-energyText',
    selectedEnergy: 'com.dometicapp:id/climate-selectedEnergy',
    energyCollapse: 'com.dometicapp:id/climate-energyContainericonCollapse',
    acModeContainer: 'com.dometicapp:id/climate-acModeContainer',
    acModeText: 'com.dometicapp:id/climate-acModeText',
    selectedMode: 'com.dometicapp:id/climate-selectedMode',
    acModeCollapse: 'com.dometicapp:id/climate-acModeiconCollapse',
    fanSpeedContainer: 'com.dometicapp:id/climate-fanSpeedContainer',
    fanSpeedText: 'com.dometicapp:id/climate-fanSpeedText',
    fanSpeedValue: 'com.dometicapp:id/climate-getAcFanSpeed',
    fanSpeedCollapse: 'com.dometicapp:id/climate-fanSpeediconCollapse',
    acText: 'com.dometicapp:id/climate-acText',
    heaterText: 'com.dometicapp:id/climate-heaterText',
    buttonList: 'com.dometicapp:id/climate-buttonList',
    placeHolderText: 'com.dometicapp:id/climate-placeHolderText',
    flatList: 'com.dometicapp:id/climate-flatList',
    flatListComponent: 'com.dometicapp:id/climate-flatListComponent',
    flatListItem: 'com.dometicapp:id/climate-flatListItem',
    allClimate: 'com.dometicapp:id/climate-allClimate',
    autoFanMode: 'com.dometicapp:id/climate-autoFanMode',
    climateMode: 'com.dometicapp:id/climate-climateMode',
    climateAgs: 'com.dometicapp:id/climate-climateAgs',
    airConditioner: 'com.dometicapp:id/climate-airConditioner',
    scheduler: 'com.dometicapp:id/climate-schedulerMode',
    temperature: 'com.dometicapp:id/climate-temperature',
    scheduledAt: 'com.dometicapp:id/climate-scheduledAt',
    scheduledDays: 'com.dometicapp:id/climate-scheduledDays',
    heatPump: 'com.dometicapp:id/climate-heatPump',
    heatSource: 'com.dometicapp:id/climate-heatSource',
    furnace: 'com.dometicapp:id/climate-furnace',
    sleepModifier: 'com.dometicapp:id/climate-sleepModifier',
    ecoModifier: 'com.dometicapp:id/climate-ecoModifier',
    schdulerButtonList: 'com.dometicapp:id/climate-schdulerButtonList',
    schdulerButton: 'com.dometicapp:id/climate-schdulerButton',
    autoFanModeButton: 'com.dometicapp:id/climate-autoFanModeButton',
    climateZoneFlatList: 'com.dometicapp:id/climate-zoneFlatList',
    spinner: 'com.dometicapp:id/climate-spinner',
  },
  ClimateMTC: {
    backgroundImage: 'com.dometicapp:id/climateMTC-backgroundImage',
  },
  Scenes: {
    backgroundImage: 'com.dometicapp:id/scenes-backgroundImage',
    container: 'com.dometicapp:id/scenes-container',
    sceneView: 'com.dometicapp:id/scenes-sceneView',
    sceneComponent: 'com.dometicapp:id/scenes-sceneComponent',
    sceneComponentText: 'com.dometicapp:id/scenes-sceneComponentText',
    flatListComponent: 'com.dometicapp:id/scenes-flatListComponent',
    flatListItem: 'com.dometicapp:id/scenes-flatListItem',
    flatList: 'com.dometicapp:id/scenes-flatList',
    customToast: 'com.dometicapp:id/scenes-customToast',
    addScenesIcon: 'com.dometicapp:id/zoneManagement-addZoneIcon',
    addScenesText: 'com.dometicapp:id/zoneManagement-addZoneText',
  },
  ScenesInfo: {
    background: 'com.dometicapp:id/scenesInfo-background',
    header: 'com.dometicapp:id/scenesInfo-header',
  },
  AddScenesInfo: {
    header: 'com.dometicapp:id/addScenesInfo-header',
  },
  Automation: {
    backgroundImage: 'com.dometicapp:id/automation-backgroundImage',
    container: 'com.dometicapp:id/automation-container',
    flatListComponent: 'com.dometicapp:id/automation-flatListComponent',
    flatListItem: 'com.dometicapp:id/automation-flatListItem',
    customToast: 'com.dometicapp:id/automation-customToast',
    timerComponent: 'com.dometicapp:id/automation-timerComponent',
    listEmptyText: 'com.dometicapp:id/automation-listEmptyText',
    addAutomationButton: 'com.dometicapp:id/automation-addAutomationButton',
    addAutomationIcon: 'com.dometicapp:id/automation-addAutomationIcon',
    addAutomationText: 'com.dometicapp:id/automation-addAutomationText',
    listItem: 'com.dometicapp:id/automation-listItem',
    listItemDeleteButton: 'com.dometicapp:id/automation-listItemDeleteButton',
    listItemDeleteIcon: 'com.dometicapp:id/automation-listItemDeleteIcon',
    listItemContent: 'com.dometicapp:id/automation-listItemContent',
    listItemTitle: 'com.dometicapp:id/automation-listItemTitle',
    listItemTimeContent: 'com.dometicapp:id/automation-listItemTimeContent',
    listItemTime: 'com.dometicapp:id/automation-listItemTime',
    listItemPeriod: 'com.dometicapp:id/automation-listItemPeriod',
    listItemDays: 'com.dometicapp:id/automation-listItemDays',
    listItemRightArrowIcon:
      'com.dometicapp:id/automation-listItemRightArrowIcon',
  },
  AddAutomation: {
    backgroundImage: 'com.dometicapp:id/automation-backgroundImage',
    header: 'com.dometicapp:id/automation-header',
    scrollView: 'com.dometicapp:id/automation-scrollView',
    nameContainer: 'com.dometicapp:id/automation-nameContainer',
    nameText: 'com.dometicapp:id/automation-nameText',
    nameInput: 'com.dometicapp:id/automation-nameInput',
    sceneContainer: 'com.dometicapp:id/automation-sceneContainer',
    sceneText: 'com.dometicapp:id/automation-sceneText',
    scenePicker: 'com.dometicapp:id/automation-scenePicker',
    selectedSceneText: 'com.dometicapp:id/automation-selectedSceneText',
    scenePickerArrowIcon: 'com.dometicapp:id/automation-scenePickerArrowIcon',
    actionSheet: 'com.dometicapp:id/automation-actionSheet',
    selectDaysContainer: 'com.dometicapp:id/automation-selectDaysContainer',
    daysSelector: 'com.dometicapp:id/automation-daysSelector',
    schedulerText: 'com.dometicapp:id/automation-schedulerText',
    schdulerMeridianButton:
      'com.dometicapp:id/automation-schdulerMeridianButton',
    timerComponent: 'com.dometicapp:id/automation-timerComponent',
  },
  ActionSheet: {
    modal: 'com.dometicapp:id/automation-modal',
    mainContainer: 'com.dometicapp:id/automation-mainContainer',
    header: 'com.dometicapp:id/automation-header',
    title: 'com.dometicapp:id/automation-title',
    closeButton: 'com.dometicapp:id/automation-closeButton',
    closeIcon: 'com.dometicapp:id/automation-closeIcon',
    list: 'com.dometicapp:id/automation-list',
    listItem: 'com.dometicapp:id/automation-listItem',
    listItemText: 'com.dometicapp:id/automation-listItemText',
  },
  Tiles: {
    // Element id constants for Tiles screen
    backgroundImage: 'com.dometicapp:id/tiles-backgroundImage',
    spinner: 'com.dometicapp:id/tiles-spinner',
    headerComponent: 'com.dometicapp:id/tiles-headerComponent',
    lastShadowText: 'com.dometicapp:id/tiles-lastShadowText',
    refreshControl: 'com.dometicapp:id/tiles-refreshControl',
    flatGrid: 'com.dometicapp:id/tiles-flatGrid',
    tiles: 'com.dometicapp:id/tiles',
    whatsNewScreenOverlay: 'com.dometicapp:id/tiles-whatsNewScreenOverlay',
    whatsNewContainer: 'com.dometicapp:id/tiles-whatsNewScreenContainer',
    whatsNewScrollView: 'com.dometicapp:id/tiles-whatsNewScreenScrollView',
    overlaySuccess: 'com.dometicapp:id/tiles-overlaySuccess',
    closeContainer: 'com.dometicapp:id/tiles-closeContainer',
    overlayCloseIcon: 'com.dometicapp:id/tiles-overlayCloseIcon',
    successfulPairingText: 'com.dometicapp:id/tiles-successfulPairing',
    closeWindow: 'com.dometicapp:id/tiles-closeWindow',
    dometicAppText: 'com.dometicapp:id/tiles-dometicAppText',
    userGuide: 'com.dometicapp:id/tiles-userGuide',
    pleaseText: 'com.dometicapp:id/tiles-pleaseText',
    clickHereButton: 'com.dometicapp:id/tiles-clickHereButton',
    clickHeretext: 'com.dometicapp:id/tiles-clickHeretext',
    checkedIcon: 'com.dometicapp:id/tiles-checkedIconSuccessfulPairing',
    uncheckedIcon: 'com.dometicapp:id/tiles-uncheckedIconSuccessfulPairing',
    checkboxContainer:
      'com.dometicapp:id/tiles-checkBoxContainerSuccessfulPairing',
    carouselContainer: 'com.dometicapp:id/tiles-carouselContainer',
    carouselClose: 'com.dometicapp:id/tiles-carouselClose',
    iconClose: 'com.dometicapp:id/tiles-iconClose',
    title: 'com.dometicapp:id/tiles-title',
    carouselRenderItem: 'com.dometicapp:id/tiles-carouselRenderItem',
    carouselPagination: 'com.dometicapp:id/tiles-carouselPagination',
    checkeBoxCarousel: 'com.dometicapp:id/tiles-checkboxBase',
    checkedIconCarousel: 'com.dometicapp:id/tiles-checkedIcon',
    uncheckedIconCarousel: 'com.dometicapp:id/tiles-uncheckedIcon',
    checkboxCarouselContainer: 'com.dometicapp:id/tiles-checkboxContainer',
    carouselData: 'com.dometicapp:id/tiles-carouselData',
    caouselItem: 'com.dometicapp:id/tiles-carouselItem',
    viewOptionsOverlay: 'com.dometicapp:id/tiles-viewOptionsOverlay',
    viewOptionsContainer: 'com.dometicapp:id/tiles-viewOptionsContainer',
    viewOptionsCloseIcon: 'com.dometicapp:id/tiles-viewOptionsCloseIcon',
    viewOptionsTextConatiner:
      'com.dometicapp:id/tiles-viewOptionsTextConatiner',
    viewOptionsGridConatiner:
      'com.dometicapp:id/tiles-viewOptionsGridConatiner',
    viewOptionsGridTextConatiner:
      'com.dometicapp:id/tiles-viewOptionsGridTextConatiner',
    viewOptionsGridTextIconConatiner:
      'com.dometicapp:id/tiles-viewOptionsGridTextIconConatiner',
    viewOptionsListConatiner:
      'com.dometicapp:id/tiles-viewOptionsListConatiner',
    viewOptionsListTextConatiner:
      'com.dometicapp:id/tiles-viewOptionsListTextConatiner',
    viewOptionsListTextIconConatiner:
      'com.dometicapp:id/tiles-viewOptionsListTextIconConatiner',
    flatList: 'com.dometicapp:id/viewOptions-flatList',
    flatListItem: 'com.dometicapp:id/viewOptions-flatListItem',
  },
  HeaderBackImage: {
    // Element id constants for HeaderBackImage screen
    backImage: 'com.dometicapp:id/tiles-backImage',
    container: 'com.dometicapp:id/tiles-container',
  },
  HeaderRightClose: {
    // Element id constants for HeaderRightClose screen
    closeImage: 'com.dometicapp:id/headerRightClose-closeImage',
    container: 'com.dometicapp:id/headerRightClose-container',
  },
  Settings: {
    // Element id constants for Settings screen
    backgroundImage: 'com.dometicapp:id/setting-backgroundImage',
    scrollView: 'com.dometicapp:id/setting-scrollView',
    languageContainer: 'com.dometicapp:id/setting-languageContainer',
    languageText: 'com.dometicapp:id/setting-languageText',
    firmwareText: 'com.dometicapp:id/setting-firmwareText',
    selectedLanguage: 'com.dometicapp:id/setting-selectedLanguage',
    languageExpandIcon: 'com.dometicapp:id/setting-languageExpandIcon',
    temperatureContainer: 'com.dometicapp:id/setting-temperatureContainer',
    temperatureButton: 'com.dometicapp:id/setting-temperatureButtons',
    versionContainer: 'com.dometicapp:id/setting-versionContainer',
    versionText: 'com.dometicapp:id/setting-versionText',
    versionValue: 'com.dometicapp:id/setting-versionValue',
    logOutContainer: 'com.dometicapp:id/setting-logOutContainer',
    logOutText: 'com.dometicapp:id/setting-logOutText',
    fahrenheitText: 'com.dometicapp:id/setting-fahrenheitText',
    celsiusText: 'com.dometicapp:id/setting-celsiusText',
    notificationContainer: 'com.dometicapp:id/setting-notificationContainer',
    notificationText: 'com.dometicapp:id/setting-notificationText',
    notificationIcon: 'com.dometicapp:id/setting-notificationIcon',
    unitContainer: 'com.dometicapp:id/setting-unitContainer',
    unitText: 'com.dometicapp:id/setting-unitText',
    selectedUnit: 'com.dometicapp:id/setting-selectedUnit',
    unitExpandIcon: 'com.dometicapp:id/setting-unitExpandIcon',
  },
  Languages: {
    // Element id constants for Languages screen
    backgroundImage: 'com.dometicapp:id/language-backgroundImage',
    scrollView: 'com.dometicapp:id/language-scrollView',
    englishContainer: 'com.dometicapp:id/language-englishContainer',
    englishText: 'com.dometicapp:id/language-englishText',
    iconTickEnglish: 'com.dometicapp:id/language-iconTickEnglish',
    germanContainer: 'com.dometicapp:id/language-germanContainer',
    germanText: 'com.dometicapp:id/language-germanText',
    iconTickGerman: 'com.dometicapp:id/language-iconTickGerman',
    flatListComponent: 'com.dometicapp:id/language-flatListComponent',
    flatListItem: 'com.dometicapp:id/language-flatListItem',
    german: 'com.dometicapp:id/language-german',
    english: 'com.dometicapp:id/language-english',
    french: 'com.dometicapp:id/language-french',
    spanish: 'com.dometicapp:id/language-spanish',
  },
  Notifications: {
    // Element id constants for Notifications screen
    backgroundImage: 'com.dometicapp:id/notification-backgroundImage',
    header: 'com.dometicapp:id/notification-header',
    scrollView: 'com.dometicapp:id/notification-scrollView',
    pushNotification:
      'com.dometicapp:id/notification-pushNotificationContainer',
    emailContainer: 'com.dometicapp:id/notification-emailContainer',
    smsContainer: 'com.dometicapp:id/notification-smsContainer',
    pushNotificationAlert:
      'com.dometicapp:id/notification-pushNotificationAlert',
    pushNotificationWarning:
      'com.dometicapp:id/notification-pushNotificationWarning',
    emailList: 'com.dometicapp:id/notification-emailList',
    emailNotification: 'com.dometicapp:id/notification-emailNotification',
    emailNotificationAlert:
      'com.dometicapp:id/notification-emailNotificationAlert',
    emailNotificationWarning:
      'com.dometicapp:id/notification-emailNotificationWarningContainer',
    smsList: 'com.dometicapp:id/notification-smsList',
    smsNotification: 'com.dometicapp:id/notification-smsNotification',
    smsNotificationAlert: 'com.dometicapp:id/notification-smsNotificationAlert',
    smsNotificationWarning:
      'com.dometicapp:id/notification-smsNotificationWarning',
    pushNotificationShowMore:
      'com.dometicapp:id/notification-pushNotificationShowMore',
    smsShowMore: 'com.dometicapp:id/notification-smsShowMore',
    emailShowMore: 'com.dometicapp:id/notification-emailShowMore',
    advanceText: 'com.dometicapp:id/notification-advanceText',
    notification: 'com.dometicapp:id/notification',
    devicePushNotification:
      'com.dometicapp:id/notification-devicePushNotifications',
    deviceEmailNotifications:
      'com.dometicapp:id/notification-deviceEmailNotifications',
    deviceSmsNotifications:
      'com.dometicapp:id/notification-deviceSmsNotifications',
    deviceNotification: 'com.dometicapp:id/notification-deviceNotification',
    deviceNotificationHeader:
      'com.dometicapp:id/notification-deviceNotificationHeader',
  },
  EditList: {
    container: 'com.dometicapp:id/editList-container',
    header: 'com.dometicapp:id/editList-header',
    scrollView: 'com.dometicapp:id/editList-scrollView',
    backgroundImage: 'com.dometicapp:id/editList-backgroundImage',
    listTitle: 'com.dometicapp:id/editList-listTitle',
    mainAccount: 'com.dometicapp:id/editList-mainAccount',
    aditionalAccounts: 'com.dometicapp:id/editList-aditionalAccounts',
    editListElement: 'com.dometicapp:id/editListElement',
    addElement: 'com.dometicapp:id/editList-addElement',
    save: 'com.dometicapp:id/editList-save',
  },
  ZoneManagement: {
    backgroundImage: 'com.dometicapp:id/zoneManagement-backgroundImage',
    headerComponent: 'com.dometicapp:id/zoneManagement-headerComponent',
    limitedText: 'com.dometicapp:id/zoneManagement-limitedText',
    addZoneIcon: 'com.dometicapp:id/zoneManagement-addZoneIcon',
    addZoneText: 'com.dometicapp:id/zoneManagement-addZoneText',
    flatList: 'com.dometicapp:id/zoneManagement-flatList',
    flatListItem: 'com.dometicapp:id/zoneManagement-flatListItem',
    dialog: 'com.dometicapp:id/zoneManagement-dialog',
    deleteZoneAlert: 'com.dometicapp:id/zoneManagement-deleteZoneAlert',
    addZoneBtn: 'com.dometicapp:id/zoneManagement-addZoneButton',
    zoneText: 'com.dometicapp:id/zoneManagement-zoneText',
    zoneRemoveBtn: 'com.dometicapp:id/zoneManagement-zoneRemoveBtn',
    zoneRenameText: 'com.dometicapp:id/zoneManagement-zoneRenameText',
    zoneRenameBtn: 'com.dometicapp:id/zoneManagement-zoneRenameBtn',
  },
  ZoneNumber: {
    backgroundImage: 'com.dometicapp:id/ZoneNumber-backgroundImage',
    zoneText: 'com.dometicapp:id/ZoneNumber-zoneText',
    addZoneButton: 'com.dometicapp:id/ZoneNumber-addZoneButton',
    addZoneText: 'com.dometicapp:id/ZoneNumber-addZoneText',
    selectButton: 'com.dometicapp:id/ZoneNumber-selectButton',
    selectZoneText: 'com.dometicapp:id/ZoneNumber-selectZoneText',
    zoneNumberSelection: 'com.dometicapp:id/ZoneNumber-zoneNumberSelection',
    dialog: 'com.dometicapp:id/ZoneNumber-dialog',
    CarouselComponent: 'CarouselComponent',
    textZ: 'textZ',
    save: 'saveButton',
    cancel: 'cancelButton',
    description: 'description',
    container: 'container',
  },
  Power: {
    // Element id constants for Power screen
    backgroundImage: 'com.dometicapp:id/powerScreen-backgroundImage',
    container: 'com.dometicapp:id/powerScreen-container',
    progressBar: 'com.dometicapp:id/powerScreen-progressBar',
    header: 'com.dometicapp:id/powerScreen-header',
    houseBatteryText: 'com.dometicapp:id/powerScreen-houseBatteryText',
    chargeBatteryText: 'com.dometicapp:id/powerScreen-chargeBatteryText',
    chargingText: 'com.dometicapp:id/powerScreen-chargingText',
    fullyChargedText: 'com.dometicapp:id/powerScreen-fullyChargedText',
    scrollView: 'com.dometicapp:id/powerScreen-scrollView',
    batteryVoltageText: 'com.dometicapp:id/powerScreen-batteryVoltageText',
    batteryVoltageValue: 'com.dometicapp:id/powerScreen-batteryVoltageValue',
    batteryVoltagevoltText:
      'com.dometicapp:id/powerScreen-batteryVoltagevoltText',
    currentContainer: 'com.dometicapp:id/powerScreen-currentContainer',
    currentText: 'com.dometicapp:id/powerScreen-currentText',
    currentValue: 'com.dometicapp:id/powerScreen-currentValue',
    ampereText: 'com.dometicapp:id/powerScreen-ampereText',
    timeContainer: 'com.dometicapp:id/powerScreen-timeContainer',
    timeText: 'com.dometicapp:id/powerScreen-timeText',
    timeValue: 'com.dometicapp:id/powerScreen-timeValue',
    hourText: 'com.dometicapp:id/powerScreen-hourText',
    powerSourceContainer: 'com.dometicapp:id/powerScreen-powerSourceContainer',
    powerSourceText: 'com.dometicapp:id/powerScreen-powerSourceText',
    powerSourceValue: 'com.dometicapp:id/powerScreen-powerSourceValue',
    powerSourcevoltText: 'com.dometicapp:id/powerScreen-powerSourcevoltText',
    powerFlatList: 'com.dometicapp:id/powerScreen-flatList',
    powerFlatListItem: 'com.dometicapp:id/powerScreen-flatListItem',
    controller: 'com.dometicapp:id/powerScreen-controller',
    startButton: 'com.dometicapp:id/powerScreen-startButton',
    stopButton: 'com.dometicapp:id/powerScreen-stopButton',
    emptyAfterVoltage: 'com.dometicapp:id/powerScreen-emptyAfterVoltage',
    measuredVoltage: 'com.dometicapp:id/powerScreen-measuredVoltage',
    status: 'com.dometicapp:id/powerScreen-status',
    emptyAfterStatus: 'com.dometicapp:id/powerScreen-emptyAfterStatus',
    usage: 'com.dometicapp:id/powerScreen-usage',
    emptyAfterUsage: 'com.dometicapp:id/powerScreen-emptyAfterUsage',
    alert: 'com.dometicapp:id/powerScreen-alert',
    emptyAfterAlert: 'com.dometicapp:id/powerScreen-emptyAfterAlert',
    notify: 'com.dometicapp:id/powerScreen-notify',
    batteryVoltage: 'com.dometicapp:id/powerScreen-batteryVoltage',
    batteryCarousel: 'com.dometicapp:id/powerScreen-batteryCarousel',
    inverter: 'com.dometicapp:id/powerScreen-inverter',
    operatingMode: 'com.dometicapp:id/powerScreen-operatingMode',
    houseBattery: 'com.dometicapp:id/powerScreen-houseBattery',
    loadWattage: 'com.dometicapp:id/powerScreen-loadWattage',
    chassisBattery: 'com.dometicapp:id/powerScreen-chassisBattery',
    generator: 'com.dometicapp:id/powerScreen-generator',
    charger: 'com.dometicapp:id/powerScreen-charger',
    ags: 'com.dometicapp:id/powerScreen-ags',
    predictiveData: 'com.dometicapp:id/powerScreen-predictiveData',
    spinner: 'com.dometicapp:id/powerScreen-spinner',
  },
  powerPredictiveData: {
    barChart: 'com.dometicapp:id/predictiveDataScreen-barChart',
    predictiveDataTitle: 'com.dometicapp:id/powerScreen-predictiveDataTitle',
    barChartYaxisLabel: 'com.dometicapp:id/powerScreen-barChartYaxisLabel',
    barChartXaxisLabel: 'com.dometicapp:id/powerScreen-barChartXaxisLabel',
  },
  Battery: {
    voltageGraph: 'com.dometicapp:id/batteryScreen-voltageGraph',
    alertsBattery: 'com.dometicapp:id/batteryScreen-alertsBattery',
    alertsBatteryBelowVoltage:
      'com.dometicapp:id/batteryScreen-alertsBatteryBelowVoltage',
    alertSetLatency: 'com.dometicapp:id/batteryScreen-alertSetLatency',
    warningBattery: 'com.dometicapp:id/batteryScreen-warningBattery',
    warningsBatteryBelowVoltage:
      'com.dometicapp:id/batteryScreen-warningsBatteryBelowVoltage',
    warningSetLatency: 'com.dometicapp:id/batteryScreen-warningSetLatency',
  },
  Tracking: {
    mapView: 'com.dometicapp:id/tracking-mapView',
    mapMarker: 'com.dometicapp:id/tracking-mapMarker',
    mapCircle: 'com.dometicapp:id/tracking-mapCircle',
    boatLocation: 'com.dometicapp:id/tracking-location',
    latitude: 'com.dometicapp:id/tracking-latitude',
    longitude: 'com.dometicapp:id/tracking-longitude',
    geofencing: 'com.dometicapp:id/tracking-geofencing',
    geofencingRadius: 'com.dometicapp:id/tracking-geofencingRadius',
    geofencingLatency: 'com.dometicapp:id/tracking-geofencingLatency',
    mapViewClose: 'com.dometicapp:id/tracking-mapViewClose',
  },
  Security: {
    armButton: 'com.dometicapp:id/security-armButton',
    armButtonText: 'com.dometicapp:id/security-armButtonTxt',
    armButtonInfoLabel: 'com.dometicapp:id/security-armButtonInfoLabel',
    securityCurrentStatus: 'com.dometicapp:id/securityCurrentStatus',
    armIcon: 'com.dometicapp:id/security-armIcon',
    geofencing: 'com.dometicapp:id/security-geofencing',
    geofencingRadius: 'com.dometicapp:id/security-geofencingRadius',
    geofencingLatency: 'com.dometicapp:id/security-geofencingLatency',
    doorAlert: 'com.dometicapp:id/security-doorAlert',
    doorLatency: 'com.dometicapp:id/security-door-alertLatency',
    theftAlert: 'com.dometicapp:id/security-theftAlert',
    theftAlertLatency: 'com.dometicapp:id/security-theftAlertLatency',
  },
  AcMode: {
    // Element id constants for AcMode screen
    backgroundImage: 'com.dometicapp:id/acMode-backgroundImage',
    container: 'com.dometicapp:id/acMode-container',
    insideTemp: 'com.dometicapp:id/acMode-insideTemp',
    insideTempValue: 'com.dometicapp:id/acMode-insideTempValue',
    insideTempUnit: 'com.dometicapp:id/acMode-insideTempUnit',
    outsideTemp: 'com.dometicapp:id/acMode-outsideTemp',
    outsideTempValue: 'com.dometicapp:id/acMode-outsideTempValue',
    outsideTempUnit: 'com.dometicapp:id/acMode-outsideTempUnit',
    acTemperature: 'com.dometicapp:id/acMode-temperature',
    applyChangesText: 'com.dometicapp:id/acMode-applyChangesText',
    fanIcon: 'com.dometicapp:id/acMode-fanIcon',
    fanSpeed: 'com.dometicapp:id/acMode-getAcFanSpeed',
    acModeText: 'com.dometicapp:id/acMode-acmodeText',
    applyButton: 'com.dometicapp:id/acMode-applyButton',
    applyText: 'com.dometicapp:id/acMode-applyText',
    acModeValues: 'com.dometicapp:id/acMode-acmodeValue',
    acModeItemValues: 'com.dometicapp:id/acMode-acmodeItemValue',
  },
  HeatSource: {
    backgroundImage: 'com.dometicapp:id/heatSource-backgroundImage',
    container: 'com.dometicapp:id/heatSource-container',
    insideTemp: 'com.dometicapp:id/heatSource-insideTemp',
    insideTempValue: 'com.dometicapp:id/heatSource-insideTempValue',
    insideTempUnit: 'com.dometicapp:id/heatSource-insideTempUnit',
    outsideTemp: 'com.dometicapp:id/heatSource-outsideTemp',
    outsideTempValue: 'com.dometicapp:id/heatSource-outsideTempValue',
    outsideTempUnit: 'com.dometicapp:id/heatSource-outsideTempUnit',
    acTemperature: 'com.dometicapp:id/heatSource-temperature',
    applyChangesText: 'com.dometicapp:id/heatSource-applyChangesText',
    fanIcon: 'com.dometicapp:id/heatSource-fanIcon',
    fanSpeed: 'com.dometicapp:id/heatSource-getAcFanSpeed',
    heatSourceText: 'com.dometicapp:id/heatSource-HeatSourceText',
    applyButton: 'com.dometicapp:id/heatSource-applyButton',
    applyText: 'com.dometicapp:id/heatSource-applyText',
    heatSourceValues: 'com.dometicapp:id/heatSource-HeatSourceValue',
    heatSourceItemValues: 'com.dometicapp:id/heatSource-heatSourceItemValue',
  },
  Scheduler: {
    backgroundImage: 'com.dometicapp:id/scheduler-backgroundImage',
    container: 'com.dometicapp:id/scheduler-container',
    insideTemp: 'com.dometicapp:id/scheduler-insideTemp',
    insideTempValue: 'com.dometicapp:id/scheduler-insideTempValue',
    insideTempUnit: 'com.dometicapp:id/scheduler-insideTempUnit',
    outsideTemp: 'com.dometicapp:id/scheduler-outsideTemp',
    outsideTempValue: 'com.dometicapp:id/scheduler-outsideTempValue',
    outsideTempUnit: 'com.dometicapp:id/scheduler-outsideTempUnit',
    acTemperature: 'com.dometicapp:id/scheduler-temperature',
    applyChangesText: 'com.dometicapp:id/scheduler-applyChangesText',
    fanIcon: 'com.dometicapp:id/scheduler-fanIcon',
    fanSpeed: 'com.dometicapp:id/scheduler-getAcFanSpeed',
    schedulerText: 'com.dometicapp:id/scheduler-schedulerText',
    applyButton: 'com.dometicapp:id/scheduler-applyButton',
    applyText: 'com.dometicapp:id/scheduler-applyText',
    schedulerValues: 'com.dometicapp:id/scheduler-schedulerValue',
    schedulerItemValues: 'com.dometicapp:id/scheduler-schedulerItemValue',
    timerComponent: 'com.dometicapp:id/scheduler-timerComponent',
    flatList: 'com.dometicapp:id/scheduler-flatList',
    temperatureArrayValue: 'com.dometicapp:id/scheduler-temperatureArrayValue',
    temperatureArray: 'com.dometicapp:id/scheduler-temperatureArray',
    buttonList: 'com.dometicapp:id/scheduler-buttonList',
    daySelectionView: 'com.dometicapp:id/scheduler-daySelectionView',
    schdulerMeridianButton: 'com.dometicapp:id/climate-schdulerMeridianButton',
  },
  FanSpeed: {
    // Element id constants for FanSpeed screen
    backgroundImage: 'com.dometicapp:id/fanSpeed-backgroundImage',
    container: 'com.dometicapp:id/fanSpeed-container',
    insideTemp: 'com.dometicapp:id/fanSpeed-insideTemp',
    insideTempValue: 'com.dometicapp:id/fanSpeed-insideTempValue',
    insideTempUnit: 'com.dometicapp:id/fanSpeed-insideTempUnit',
    outsideTemp: 'com.dometicapp:id/fanSpeed-outsideTemp',
    outsideTempValue: 'com.dometicapp:id/fanSpeed-outsideTempValue',
    outsideTempUnit: 'com.dometicapp:id/fanSpeed-outsideTempUnit',
    fanspeedTemperature: 'com.dometicapp:id/fanSpeed-temperature',
    applyChangesText: 'com.dometicapp:id/fanSpeed-applyChangesText',
    fanIcon: 'com.dometicapp:id/fanSpeed-fanIcon',
    fanSpeed: 'com.dometicapp:id/fanSpeed-getAcFanSpeed',
    fanspeedText: 'com.dometicapp:id/fanSpeed-fanspeedText',
    applyButton: 'com.dometicapp:id/fanSpeed-applyButton',
    applyText: 'com.dometicapp:id/fanSpeed-applyText',
    fanspeedValues: 'com.dometicapp:id/fanSpeed-fanSpeedValue',
    fanspeedItemValues: 'com.dometicapp:id/fanSpeed-fanSpeedItemValue',
  },
  EnergyHeater: {
    // Element id constants for EnergyHeater screen
    backgroundImage: 'com.dometicapp:id/energyHeater-backgroundImage',
    container: 'com.dometicapp:id/energyHeater-container',
    insideTemp: 'com.dometicapp:id/energyHeater-insideTemp',
    insideTempValue: 'com.dometicapp:id/energyHeater-insideTempValue',
    insideTempUnit: 'com.dometicapp:id/energyHeater-insideTempUnit',
    outsideTemp: 'com.dometicapp:id/energyHeater-outsideTemp',
    outsideTempValue: 'com.dometicapp:id/energyHeater-outsideTempValue',
    outsideTempUnit: 'com.dometicapp:id/energyHeater-outsideTempUnit',
    energyHeaterTemperature: 'com.dometicapp:id/energyHeater-temperature',
    applyChangesText: 'com.dometicapp:id/energyHeater-applyChangesText',
    energyHeaterText: 'com.dometicapp:id/energyHeater-energyheaterText',
    applyButton: 'com.dometicapp:id/energyHeater-applyButton',
    applyText: 'com.dometicapp:id/energyHeater-applyText',
    enegryHeaterValues: 'com.dometicapp:id/energyHeater-energyHeaterValue',
    energyHeaterItemValues:
      'com.dometicapp:id/energyHeater-energyHeaterItemValue',
  },
  WaterHeater: {
    // Element id constants for WaterHeater screen
    backgroundImage: 'com.dometicapp:id/waterHeater-backgroundImage',
    container: 'com.dometicapp:id/waterHeater-container',
    insideTemp: 'com.dometicapp:id/waterHeater-insideTemp',
    insideTempValue: 'com.dometicapp:id/waterHeater-insideTempValue',
    insideTempUnit: 'com.dometicapp:id/waterHeater-insideTempUnit',
    outsideTemp: 'com.dometicapp:id/waterHeater-outsideTemp',
    outsideTempValue: 'com.dometicapp:id/waterHeater-outsideTempValue',
    outsideTempUnit: 'com.dometicapp:id/waterHeater-outsideTempUnit',
    waterHeaterTemperature: 'com.dometicapp:id/waterHeater-temperature',
    applyChangesText: 'com.dometicapp:id/waterHeater-applyChangesText',
    waterHeaterText: 'com.dometicapp:id/waterHeater-waterheaterText',
    applyButton: 'com.dometicapp:id/waterHeater-applyButton',
    applyText: 'com.dometicapp:id/waterHeater-applyText',
    waterHeaterValue: 'com.dometicapp:id/waterHeater-waterHeaterValue',
    waterHeaterItemValue: 'com.dometicapp:id/waterHeater-waterHeaterItemValue',
  },
  WebView: {
    // Element id constants for WebView screen
    noInternet: 'com.dometicapp:id/webView-noInternet',
    true: true,
  },
  ResetPwd: {
    // Element id constants for ResetPwd screen
    container: 'com.dometicapp:id/resetPwd-container',
    backgroundImage: 'com.dometicapp:id/resetPwd-backgroundImage',
    resetPwd: 'com.dometicapp:id/resetPwd-resetPwd',
    selectDetails: 'com.dometicapp:id/resetPwd-selectDetails',
    resetPass: 'com.dometicapp:id/resetPwd-resetPass',
    email: 'com.dometicapp:id/resetPwd-email',
    emailField: 'com.dometicapp:id/resetPwd-emailField',
    invalidEmailText: 'com.dometicapp:id/resetPwd-invalidemail-message',
    sendButton: 'com.dometicapp:id/resetPwd-sendButton',
    haveAccount: 'com.dometicapp:id/resetPwd-haveAccount',
    gotoLogin: 'com.dometicapp:id/resetPwd-gotoLogin',
  },
  BathFan: {
    backgroundImage: 'com.dometicapp:id/bathFan-backgroundImage',
    bathFanTitle: 'com.dometicapp:id/bathFan-bathFanTitle',
    bathFanComponenPower: 'com.dometicapp:id/bathFan-bathFanComponent-power',
    bathFanComponenPowerTitle:
      'com.dometicapp:id/bathFan-bathFanComponent-power-title',
    bathFanComponenPowerStatusTitle:
      'com.dometicapp:id/bathFan-bathFanComponent-power-status-title',
    bathFanComponenPowerText:
      'com.dometicapp:id/bathFan-bathFanComponent-power-text',
    bathFanComponentLid: 'com.dometicapp:id/bathFan-bathFanComponent-lid',
    bathFanComponentLidTitle:
      'com.dometicapp:id/bathFan-bathFanComponent-lid-title',
    bathFanComponentLidStatusTitle:
      'com.dometicapp:id/bathFan-bathFanComponent-lid-status-title',
    bathFanComponenLidText:
      'com.dometicapp:id/bathFan-bathFanComponent-lid-text',
    bathFanComponenPowerSwitch:
      'com.dometicapp:id/bathFan-bathFanComponent-power-switch',
    bathFanComponentLidSwitch:
      'com.dometicapp:id/bathFan-bathFanComponent-lid-switch',
    flatListComponent: 'com.dometicapp:id/bathFan-flatListComponent',
    flatListItem: 'com.dometicapp:id/bathFan-flatListItem',
  },
  Awning: {
    // Element id constants for mechanical awning screen
    backgroundImage: 'com.dometicapp:id/awning-backgroundImage',
    awningText: 'com.dometicapp:id/awning-awningText',
    extendText: 'com.dometicapp:id/awning-extendText',
    stopButton: 'com.dometicapp:id/awning-stopButton',
    pluseImage: 'com.dometicapp:id/awning-pluseImage',
    minusImage: 'com.dometicapp:id/awning-minusImage',
    pluseButton: 'com.dometicapp:id/awning-pluseButton',
    minusButton: 'com.dometicapp:id/awning-minusButton',
    openButton: 'com.dometicapp:id/awning-openButton',
    closeButton: 'com.dometicapp:id/awning-closeButton',
  },
  Lights: {
    backgroundImage: 'com.dometicapp:id/Lights-backgroundImage',
    lightCards: 'com.dometicapp:id/Lights-lightCards',
    flatList: 'com.dometicapp:id/Lights-flatList',
    lightCard: 'com.dometicapp:id/Lights-lightCard',
    lightCardContainer: 'com.dometicapp:id/Lights-lightCardContainer',
    lightCardCategory: 'com.dometicapp:id/Lights-lightCardCategory',
    dimmer: 'com.dometicapp:id/Lights-dimmer',
    sliderView: 'com.dometicapp:id/Lights-sliderView',
    slider: 'com.dometicapp:id/Lights-slider',
    switchContainer: 'com.dometicapp:id/Lights-switchContainer',
    switch: 'com.dometicapp:id/Lights-switch',
    overlaySlider: 'com.dometicapp:id/slider-overlay-slider',
    popupOverlay: 'com.dometicapp:id/slider-popup-overlay',
    title: 'com.dometicapp:id/Lights-title',
    sliderValue: 'com.dometicapp:id/Lights-sliderValue',
    sliderValueUnit: 'com.dometicapp:id/Lights-sliderValueUnit',
  },
  Switch: {
    // Element id constants for Switch component
    switch: 'com.dometicapp:id/switch-switch',
  },
  Slider: {
    slider: 'com.dometicapp:id/slider-slider',
  },
  Alert: {
    alert: 'com.dometicapp:id/alert-alert',
  },
  CustomCard: {
    cardTitle: 'cardTitle',
    switchText: 'switchText',
    switchComponent: 'switchComponent',
    cardSubText: 'cardSubText',
    cardIcon: 'cardIcon',
    tooltip: 'tooltip',
    tickIcon: 'tickIcon',
    expandIcon: 'expandIcon',
    textButtonContainer: 'textButtonContainer',
    textButton: 'textButton',
    dropdownButton: 'dropdownButton',
    dropdownButtonText: 'dropDownButtonText',
    dropdownItem: 'dropDownItem',
    dropdownItemText: 'dropDownItemText',
  },
  BatteryCarousel: {
    circle: 'circle',
    batteryIcon: 'batteryIcon',
    batteryValue: 'batteryValue',
    batteryUnit: 'batteryUnit',
    batteryName: 'batteryName',
    batteryValueCarousel: 'batteryValueCarousel',
    batteryNameCarousel: 'batteryNameCarousel',
    batteryStatus: 'batteryStatus',
    batteryNameItem: 'batteryNameContainer',
  },
  CircleCarousel: {
    circle: 'circle',
    carouselIcon: 'carouselIcon',
    carouselValue: 'carouselValue',
    carouselUnit: 'carouselUnit',
    carouselName: 'carouselName',
    statusValue: 'statusValue',
    circleCarouselValue: 'circleCarouselValue',
    circleCarouselName: 'circleCarouselName',
    circleCarouseContainer: 'circleCarouseContainer',
    carousel24HourText: 'carousel24HourText',
  },
  TankCarousel: {
    tankCircle: 'tankCircle',
    tankIcon: 'tankIcon',
    tankValue: 'tankValue',
    tankUnit: 'tankUnit',
    tankName: 'tankName',
    tankValueCarousel: 'tankValueCarousel',
    tankNameCarousel: 'tankNameCarousel',
    tankLevel: 'tankLevel',
  },
  Accordion: {
    container: 'container',
    alerts: 'alertsSwitch',
    cardTitle: 'cardTitle',
    switchStateText: 'switchStateText',
    switchComponent: 'switchComponent',
    cardValueText: 'cardSubText',
    cardUnitText: 'cardUnitText',
    expandIcon: 'expandIcon',
    appluButton: 'flatbutton',
    applyButtonText: 'flatButtonText',
    carousalValue: 'carousalValue',
    carousalItemValue: 'carousalItemValue',
  },
  GalleyFan: {
    backgroundImage: 'com.dometicapp:id/GalleyFan-backgroundImage',
    galleyFan: 'com.dometicapp:id/GalleyFan-GalleyFanText',
    PowerComponent: 'com.dometicapp:id/GalleyFan-PowerLidContainer',
    PowerSwitch: 'com.dometicapp:id/GalleyFan-PowerSwitch',
    LidComponent: 'com.dometicapp:id/GalleyFan-LidContainer',
    LidSwitch: 'com.dometicapp:id/GalleyFan-LidSwitch',
    fanSpeedText: 'com.dometicapp:id/GalleyFan-fanSpeedText',
    CarouselContainer: 'com.dometicapp:id/GalleyFan-CarouselContainer',
    applyButton: 'com.dometicapp:id/GalleyFan-applyButton',
    VerticalCarousel: 'com.dometicapp:id/GalleyFan-VerticalCarousel',
    VerticalCarouselItem: 'com.dometicapp:id/GalleyFan-VerticalCarouselItem',
    galleyFanComponenPowerTitle:
      'com.dometicapp:id/galleyFan-galleyComponent-power-title',
    galleyFanComponenPowerStatusTitle:
      'com.dometicapp:id/galleyFan-galleyFanComponent-power-status-title',
    galleyFanComponenPowerText:
      'com.dometicapp:id/galleyFan-galleyFanComponent-power-text',
    galleyFanComponentLid: 'com.dometicapp:id/galleyFan-galleyFanComponent-lid',
    galleyFanComponentLidTitle:
      'com.dometicapp:id/galleyFan-galleyFanComponent-lid-title',
    galleyFanComponentLidStatusTitle:
      'com.dometicapp:id/galleyFan-galleyFanComponent-lid-status-title',
    galleyFanComponenLidText:
      'com.dometicapp:id/galleyFan-galleyFanComponent-lid-text',
    galleyFanComponenPowerSwitch:
      'com.dometicapp:id/galleyFan-galleyFanComponent-power-switch',
    galleyFanComponentLidSwitch:
      'com.dometicapp:id/galley-galleyFanComponent-lid-switch',
    flatListComponent: 'com.dometicapp:id/galley-flatListComponent',
    flatListItem: 'com.dometicapp:id/galley-flatListItem',
  },
  BarChart: {
    xAxis: 'com.dometicapp:id/BarChart-xAxis',
    yAxis: 'com.dometicapp:id/BarChart-yAxis',
    barChart: 'com.dometicapp:id/BarChart-barChart',
    barChartContainer: 'com.dometicapp:id/BarChart-barChartContainer',
  },
  TrumaWaterHeater: {
    verticalCarouselItem:
      'com.dometicapp:id/trumaWaterHeater-VerticalCarouselItem',
    verticalCarousel: 'com.dometicapp:id/trumaWaterHeater-VerticalCarousel',
    waterHeaterStatusText:
      'com.dometicapp:id/trumaWaterHeater-waterHeaterStatusText',
    carouselContainer: 'com.dometicapp:id/trumaWaterHeater-CarouselContainer',
    applyButton: 'com.dometicapp:id/trumaWaterHeater-applyButton',
    backgroundImage: 'com.dometicapp:id/trumaWaterHeater-backgroundImage',
    heaterComponent: 'com.dometicapp:id/trumaWaterHeater-heaterContainer',
    waterHeaterComponenHeaterTitle:
      'com.dometicapp:id/trumaWaterHeater-waterHeaterComponent-heater-title',
    waterHeaterComponenHeaterStatusTitle:
      'com.dometicapp:id/trumaWaterHeater-waterHeaterComponent-heater-status-title',
    waterHeaterComponenHeaterText:
      'com.dometicapp:id/trumaWaterHeater-waterHeaterComponent-heater-text',
    heaterSwitch: 'com.dometicapp:id/trumaWaterHeater-heaterSwitch',
    waterHeaterStatus:
      'com.dometicapp:id/trumaWaterHeater-waterHeaterStatusText',
    waterHeaterStatusValue:
      'com.dometicapp:id/trumaWaterHeater-waterHeaterStatusValue',
    carouselHeader: 'com.dometicapp:id/trumaWaterHeater-carouselHeader',
    carouselHeaderBorder:
      'com.dometicapp:id/trumaWaterHeater-carouselHeaderBorder',
    modeCollapse: 'com.dometicapp:id/trumaWaterHeater-modeCollapse',
    modeText: 'com.dometicapp:id/trumaWaterHeater-modeText',
    modeValue: 'com.dometicapp:id/trumaWaterHeater-modeValue',
    decalcification: 'com.dometicapp:id/trumaWaterHeater-decalcification',
  },
  Tank: {
    tank: 'com.dometicapp:id/Tank',
    backgroundImage: 'com.dometicapp:id/Tank-backgroundImage',
    progressIndicator: 'com.dometicapp:id/Tank-progressIndicator',
    progressIndicatorTitle: 'com.dometicapp:id/Tank-progressIndicatorTitle',
    waterPump: 'com.dometicapp:id/Tank-waterPump',
    flatList: 'com.dometicapp:id/Tank-flatList',
    flatListItem: 'com.dometicapp:id/Tank-flatListItem',
    buttons: 'com.dometicapp:id/Tank-buttons',
    predictiveAnalytics: 'com.dometicapp:id/Tank-predictiveAnalytics',
    blackWaterEmpty: 'com.dometicapp:id/Tank-blackWaterEmpty',
    circleCarousel: 'com.dometicapp:id/Tank-circleCarousel',
    alerts: 'com.dometicapp:id/Tank-alerts',
    alertTankLevelAbove: 'com.dometicapp:id/Tank-alertTankLevelAbove',
    alertSetLatency: 'com.dometicapp:id/Tank-alertSetLatency',
    warning: 'com.dometicapp:id/Tank-warning',
    warningTankLevelAbove: 'com.dometicapp:id/Tank-warningTankLevelAbove',
    warningSetLatency: 'com.dometicapp:id/Tank-warningSetLatency',
    predictiveText: 'com.dometicapp:id/Tank-predictiveText',
    expandIcon: 'com.dometicapp:id/Tank-predictData-expandIcon',
    batteryLevel: 'com.dometicapp:id/Tank-batteryLevel',
    bluetoothSignal: 'com.dometicapp:id/Tank-bluetoothSignal',
    macAddress: 'com.dometicapp:id/Tank-macAddress',
    softwareVersion: 'com.dometicapp:id/Tank-softwareVersion',
  },
  Buttons: {
    buttonId: 'com.dometicapp:id/Buttons-buttonId',
    button: 'com.dometicapp:id/Buttons-button',
    buttonsList: 'com.dometicapp:id/Buttons-buttonsList',
  },
  Ags: {
    // Element id constants for Ags screen
    backgroundImage: 'com.dometicapp:id/ags-backgroundImage',
    flatList: 'com.dometicapp:id/ags-flatList',
    flatListItem: 'com.dometicapp:id/ags-flatListItem',
    quietTimeStart: 'com.dometicapp:id/quietTimeStart',
    quietTimeEnd: 'com.dometicapp:id/quietTimeEnd',
    timeUnder: 'com.dometicapp:id/timeUnder',
    startTime: 'com.dometicapp:id/startTime',
  },
  SelectedDays: {
    // Element id constants for days selection component
    cardTitle: 'cardTitle',
    daysContainer: 'daysContainer',
    dayButton: 'dayButton',
  },
  RoundButton: {
    // Element id constants for round button component
    buttonContainer: 'buttonContainer',
    buttonImage: 'buttonImage',
    buttonText: 'buttonText',
  },
  tooltipComponent: {
    // Element id constants for tooltip component
    toolImage: 'toolImage',
    toolContent: 'toolContent',
    toolButton: 'toolButton',
  },
  meridiemComponent: {
    // Element id constants for meridiem component
    leftText: 'leftText',
    rightText: 'rightText',
    leftButton: 'leftButton',
    rightButton: 'rightButton',
  },
  startVoltage: {
    // Element id constants for Strat Voltage screen
    backgroundImage: 'com.dometicapp:id/startVoltage-backgroundImage',
    headingText: 'com.dometicapp:id/startVoltage-headingText',
    applyButton: 'com.dometicapp:id/startVoltage-applyButton',
    applyText: 'com.dometicapp:id/startVoltage-applyText',
    voltageCarousel: 'com.dometicapp:id/startVoltage-voltageCarousel',
    voltageCarouselItem: 'com.dometicapp:id/startVoltage-voltageCarouselItem',
    voltText: 'com.dometicapp:id/startVoltage-voltstext',
  },
  timeUnderScreen: {
    // Element id constants for Strat Voltage screen
    backgroundImage: 'com.dometicapp:id/timeUnder-backgroundImage',
    headingText: 'com.dometicapp:id/timeUnder-headingText',
    applyButton: 'com.dometicapp:id/timeUnder-applyButton',
    applyText: 'com.dometicapp:id/timeUnder-applyText',
    timeCarousel: 'com.dometicapp:id/timeUnder-timeCarousel',
    timeCarouselItem: 'com.dometicapp:id/timeUnder-timeCarouselItem',
    minText: 'com.dometicapp:id/timeUnder-minText',
  },
  runTime: {
    // Element id constants for Run time screen
    backgroundImage: 'com.dometicapp:id/runTime-backgroundImage',
    headingText: 'com.dometicapp:id/runTime-headingText',
    applyButton: 'com.dometicapp:id/runTime-applyButton',
    textInput: 'com.dometicapp:id/runTime-textInput',
    minText: 'com.dometicapp:id/runTime-minText',
    infoText: 'com.dometicapp:id/runTime-infoText',
    errorText: 'com.dometicapp:id/runTime-errorText',
    applyText: 'com.dometicapp:id/runTime-applyText',
    timeCarousel: 'com.dometicapp:id/runTime-timeCarousel',
    timeCarouselItem: 'com.dometicapp:id/runTime-timeCarouselItem',
  },
  TilesCard: {
    // Element id constants for TilesCard component
    // used for cards as they need to be dynamic but the initial format is same
    tileCard: 'com.dometicapp:id/tile',
    // Used for cards as they need to be dynamic and unique
    itemContainer: 'itemContainer',
    titleView: 'titleView',
    deviceOff: 'deviceOff',
    warningIcon: 'warningIcon',
    container: 'container',
    mainContentView: 'mainContentView',
    content: 'mainContent',
    unit: 'unit',
    contentContainer: 'contentContainer',
    placeHolderText: 'blank',
    footerContent: 'footerContent',
    fanIconContainer: 'fanIconContainer',
    fanIcon: 'fanIcon',
    lidStatusContainer: 'lidStatusContainer',
    lidStatus: 'lidStatus',
    warningText: 'warningText',
    warningContainer: 'warningContainer',
    fanSpeedText: 'fanSpeedText',
    applyContainer: 'climate-applyContainer',
    warningLabel: 'warningLabel',
    warningLabelText: 'warningLabelText',
    applyChanges: 'applyChangesText',
    listTileContainer: 'listTileContainer',
    notConnected: 'notConnected',
    connectNow: 'connectNow',
    connectNowText: 'connectNowText',
    mainCardText: 'mainCardText',
    mainCardSubText: 'mainCardSubText',
    cardUnitText: 'cardUnitText',
    footerIcon: 'footerIcon',
    footerText: 'footerText',
    carousel: 'carousel',
    pageControl: 'pageControl',
    fanIconText: 'com.dometicapp:id/tile-fanIconText',
    climateApply: 'com.dometicapp:id/tile-climateApply',
  },
  Header: {
    // Element id constants for Header component
    menuButton: 'com.dometicapp:id/header-menuButton',
    connectionType: 'com.dometicapp:id/header-connectionType',
    leftComponent: 'com.dometicapp:id/header-leftComponent',
    leftButton: 'com.dometicapp:id/header-leftButton',
    leftButtonImage: 'com.dometicapp:id/header-leftButtonImage',
    leftButtonText: 'com.dometicapp:id/header-leftButtonText',
    Logo: 'com.dometicapp:id/header-brandLogo',
    FilterInactive: 'com.dometicapp:id/header-Filter-Blue',
    FilterActive: 'com.dometicapp:id/header-Filter-White',
    centerTitleText: 'com.dometicapp:id/header-TitleText',
    rightButton: 'com.dometicapp:id/header-rightButton',
    rightButtonImage: 'com.dometicapp:id/header-rightButtonImage',
    rightButtonText: 'com.dometicapp:id/header-rightButtonText',
  },
  timerPicker: {
    // Element id constants for Time Picker screen
    backgroundImage: 'backgroundImage',
    headingText: 'headingText',
    applyButton: 'applyButton',
    applyText: 'applyText',
    hoursCarouselItem: 'hoursCarouselItem',
    minsCarouselItem: 'minsCarouselItem',
    hoursCarousel: 'hoursCarousel',
    minsCarousel: 'minsCarousel',
    hoursSubText: 'hoursSubText',
    minsSubText: 'minsSubText',
  },
  RemainderView: {
    remainderViewContainer: 'com.dometicapp:id/remainderView-container',
    remainderButtonClick: 'com.dometicapp:id/remainderView-buttonClick',
    remainderIconClose: 'com.dometicapp:id/remainderView-iconClose',
    remainderOnClick: 'com.dometicapp:id/remainderView-onClick',
    remainderTitleText: 'com.dometicapp:id/remainderView-title',
    remaindersubText: 'com.dometicapp:id/remainderView-subtext',
  },
  BottomCategoryTabBar: {
    categoryTabBarItem: 'com.dometicapp:id/categoryTabBarItem',
    categoryTabBarInnerView: 'com.dometicapp:id/categoryTabBarInnerView',
    categoryTabBarItemIcon: 'com.dometicapp:id/categoryTabBarItemIcon',
    categoryTabBarItemText: 'com.dometicapp:id/categoryTabBarItemText',
  },
  Switching: {
    backgroundImage: 'com.dometicapp:id/switching-backgroundImage',
    gridAll: 'com.dometicapp:id/switching-grid-all',
    gridPump: 'com.dometicapp:id/switching-grid-pump',
    gridLight: 'com.dometicapp:id/switching-grid-light',
    gridOthers: 'com.dometicapp:id/switching-grid-others',
    tabbar: 'com.dometicapp:id/switching-tabbar',
    item: 'com.dometicapp:id/switching-item',
  },
  SwitchingList: {
    itemContainer: 'itemContainer',
    itemIcon: 'icon',
    itemTitle: 'title',
    itemButtonContainer: 'buttonContainer',
    itemButton: 'button',
    up: 'up-button',
    down: 'down-button',
    progressBar: 'progressBar',
    stateName: 'stateName',
  },
  Modes: {
    backgroundImage: 'com.dometicapp:id/modes-backgroundImage',
    item: 'com.dometicapp:id/mode-item',
    gridAll: 'com.dometicapp:id/modes-grid-all',
    gridProride: 'com.dometicapp:id/modes-grid-proride',
    gridSwitching: 'com.dometicapp:id/modes-grid-switching',
    gridOthers: 'com.dometicapp:id/modes-grid-others',
    tabbar: 'com.dometicapp:id/modes-tabbar',
  },
  SideMenu: {
    container: 'com.dometicapp:id/sidemenu-container',
    userProfilePhotoContainer:
      'com.dometicapp:id/sidemenu-userProfilePhotoContainer',
    userProfilePhoto: 'com.dometicapp:id/sidemenu-userProfilePhoto',
    userEmail: 'com.dometicapp:id/sidemenu-userEmail',
    userName: 'com.dometicapp:id/sidemenu-userName',
    viewEditButton: 'com.dometicapp:id/sidemenu-viewEditButton',
    viewEditButtonText: 'com.dometicapp:id/sidemenu-viewEditButtonText',
    settingItemButton: 'com.dometicapp:id/sidemenu-settingItemButton',
    settingItemButtonText: 'com.dometicapp:id/sidemenu-settingItemButtonText',
    headerBackButtonIcon: 'com.dometicapp:id/sidemenu-headerBackButtonIcon',
    headerBackButton: 'com.dometicapp:id/sidemenu-headerBackButton',
    versionText: 'com.dometicapp:id/sidemenu-versionText',
    home: 'com.dometicapp:id/sidemenu-home',
    appSettings: 'com.dometicapp:id/sidemenu-appSettings',
    notificationSettings: 'com.dometicapp:id/sidemenu-notificationSettings',
    deviceMangagement: 'com.dometicapp:id/sidemenu-deviceMangagement',
    miniBarControl: 'com.dometicapp:id/sidemenu-miniBarControl',
    logout: 'com.dometicapp:id/sidemenu-logout',
    zoneManagement: 'com.dometicapp:id/sidemenu-zoneManagement',
  },
  UserSettings: {
    background: 'com.dometicapp:id/userSettings-background',
    userPersonalInformationFlatList:
      'com.dometicapp:id/userPersonalInformation-flatList',
    userDataSecurityFlatList: 'com.dometicapp:id/userDataSecurity-flatList',
    userPersonalInformationFlatListItem:
      'com.dometicapp:id/userPersonalInformation-flatListItem',
    userDataSecurityFlatListItem:
      'com.dometicapp:id/userDataSecurity-flatListItem',
    userProfilePhotoContainer: 'com.dometicapp:id/userSettings-photoContainer',
    userProfilePhoto: 'com.dometicapp:id/userSettings-profilePhoto',
    userEmail: 'com.dometicapp:id/userSettings-userEmail',
    userName: 'com.dometicapp:id/userSettings-userName',
    profile: 'com.dometicapp:id/userSettings-profile',
    changePassword: 'com.dometicapp:id/userSettings-changePassword',
    deleteAccount: 'com.dometicapp:id/userSettings-deleteAccount',
    subscriptions: 'com.dometicapp:id/userSettings-subscriptions',
    settingText: 'com.dometicapp:id/userSettings-settingText',
    spinner: 'com.dometicapp:id/userSettings-spinner',
    logout: 'com.dometicapp:id/userSettings-logout',
  },
  UserProfileSettingsScreen: {
    backgroundImage: 'com.dometicapp:id/userProfile-backgroundImage',
    scrollView: 'com.dometicapp:id/userProfile-scrollview',
    flatList: 'com.dometicapp:id/userProfile-flatList',
    flatListItem: 'com.dometicapp:id/userProfile-flatListItem',
    userProfilePhotoContainer: 'com.dometicapp:id/userProfile-photoContainer',
    userProfilePhoto: 'com.dometicapp:id/userProfile-photo',
    userEmailLabel: 'com.dometicapp:id/userProfile-emailLabel',
    userEmailValue: 'com.dometicapp:id/userProfile-emailValue',
    nameLabel: 'com.dometicapp:id/userProfile-nameLabel',
    nameValue: 'com.dometicapp:id/userProfile-nameValue',
    phoneLabel: 'com.dometicapp:id/userProfile-phoneLabel',
    phoneValue: 'com.dometicapp:id/userProfile-phoneValue',
    addressLabel: 'com.dometicapp:id/userProfile-addressLabel',
    addressValue: 'com.dometicapp:id/userProfile-addressValue',
    editProfile: 'com.dometicapp:id/userProfile-EditProfileButton',
    renew: 'com.dometicapp:id/userProfile-renew',
    resetPasswordText: 'com.dometicapp:id/userProfile-resetPasswordText',
    resetPasswordValue: 'com.dometicapp:id/userProfile-resetPasswordValue',
    personalInfo: 'com.dometicapp:id/userProfile-personalInfoText',
    security: 'com.dometicapp:id/userProfile-securityText',
  },
  EditProfileScreen: {
    backgroundImage: 'com.dometicapp:id/editProfile-backgroundImage',
    scrollView: 'com.dometicapp:id/editProfile-scrollview',
    userProfilePhotoContainer: 'com.dometicapp:id/editProfile-photoContainer',
    userProfilePhoto: 'com.dometicapp:id/editProfile-photo',
    userEmailValue: 'com.dometicapp:id/editProfile-emailValue',
    firstNameLabel: 'com.dometicapp:id/editProfile-firstNameLabel',
    firstNameValue: 'com.dometicapp:id/editProfile-firstNameValue',
    lastNameLabel: 'com.dometicapp:id/editProfile-lastNameLabel',
    lastNameValue: 'com.dometicapp:id/editProfile-lastNameValue',
    phoneLabel: 'com.dometicapp:id/editProfile-phoneLabel',
    phoneValue: 'com.dometicapp:id/editProfile-phoneValue',
    phoneNumberErrorLabel: 'com.dometicapp:id/editProfile-phoneErrorLabel',
    addressLabel: 'com.dometicapp:id/editProfile-addressLabel',
    addressValue: 'com.dometicapp:id/editProfile-addressValue',
    saveButtonText: 'com.dometicapp:id/editProfile-saveButtonText',
    saveButton: 'com.dometicapp:id/editProfile-saveButton',
    spinner: 'com.dometicapp:id/editProfile-spinner',
    header: 'com.dometicapp:id/editProfile-header',
  },
  DeviceManagementScreen: {
    backgroundImage: 'com.dometicapp:id/deviceManagement-backgroundImage',
    scrollView: 'com.dometicapp:id/deviceManagement-scrollview',
    imageContainer: 'com.dometicapp:id/deviceManagement-imageContainer',
    deviceImage: 'com.dometicapp:id/deviceManagement-deviceImage',
    deviceBackgroundImage:
      'com.dometicapp:id/deviceManagement-deviceBackgroundImage',
    deviceName: 'com.dometicapp:id/deviceManagement-deviceName',
    devicetitleLabel: 'com.dometicapp:id/deviceManagement-devicetitleLabel',
    deviceNameLabel: 'com.dometicapp:id/deviceManagement-deviceNameLabel',
    deviceNameValue: 'com.dometicapp:id/deviceManagement-deviceNameValue',
    hullIdLabel: 'com.dometicapp:id/deviceManagement-hullIdLabel',
    hullIdValue: 'com.dometicapp:id/deviceManagement-hullIdValue',
    editButton: 'com.dometicapp:id/deviceManagement-editDevice',
    flatList: 'com.dometicapp:id/deviceManagement-flatList',
    flatListItem: 'com.dometicapp:id/deviceManagement-flatListItem',
    masterPin: 'com.dometicapp:id/deviceManagement-masterPin',
    guestPin: 'com.dometicapp:id/deviceManagement-guestPin',
    coolerSetting: 'com.dometicapp:id/deviceManagement-coolerSetting',
    checkForUpdates: 'com.dometicapp:id/deviceManagement-checkForUpdates',
    unregisterDelete: 'com.dometicapp:id/deviceManagement-unregisterDelete',
    pinCodeTitleText: 'com.dometicapp:id/deviceManagement-pinCodeTitleText',
    advancedTitleText: 'com.dometicapp:id/deviceManagement-advancedTitleText',
    headerWithFilterIcon:
      'com.dometicapp:id/DeviceManagement-headerWithFilterIcon',
  },
  EditDeviceScreen: {
    header: 'com.dometicapp:id/editDevice-header',
    backgroundImage: 'com.dometicapp:id/editDevice-backgroundImage',
    scrollView: 'com.dometicapp:id/editDevice-scrollview',
    imageContainer: 'com.dometicapp:id/editDevice-imageContainer',
    deviceImage: 'com.dometicapp:id/editDevice-deviceImage',
    deviceName: 'com.dometicapp:id/editDevice-deviceName',
    deviceNameLabel: 'com.dometicapp:id/editDevice-deviceNameLabel',
    deviceNameValue: 'com.dometicapp:id/editDevice-deviceNameValue',
    hullIdLabel: 'com.dometicapp:id/editDevice-hullIdLabel',
    hullIdValue: 'com.dometicapp:id/editDevice-hullIdValue',
    saveButtonText: 'com.dometicapp:id/editDevice-saveButtonText',
    saveButton: 'com.dometicapp:id/editDevice-saveButton',
  },
  powerBarGraph: {
    chartContainer: 'com.dometicapp:id/powerBarGraph-chartContainer',
    hoursButtonText: 'com.dometicapp:id/powerBarGraph-hoursButtonText',
    hoursButton: 'com.dometicapp:id/powerBarGraph-hoursButton',
    dayButtonText: 'com.dometicapp:id/powerBarGraph-dayButtonText',
    dayButton: 'com.dometicapp:id/powerBarGraph-dayButton',
    weekButtonText: 'com.dometicapp:id/powerBarGraph-weekButtonText',
    weekButton: 'com.dometicapp:id/powerBarGraph-weekButton',
    monthButtonText: 'com.dometicapp:id/powerBarGraph-monthButtonText',
    monthButton: 'com.dometicapp:id/powerBarGraph-monthButton',
    pageControl: 'com.dometicapp:id/powerBarGraph-pageControl',
  },
  Format: {
    pattern: 'com.dometicapp:id/',
  },
  sdbCoolerSettings: {
    sdbCoolerSettingsFlatList: 'com.dometicapp:id/sdbCoolerSettings-flatList',
    sdbCoolerSettingsFlatListItem:
      'com.dometicapp:id/sdbCoolerSettings-flatListItem',
    coolerStatus: 'com.dometicapp:id/sdbCoolerSettings-coolerStatus',
    scheduler: 'com.dometicapp:id/sdbCoolerSettings-scheduler',
    scheduledAt: 'com.dometicapp:id/sdbCoolerSettings-scheduledAt',
    temperature: 'com.dometicapp:id/sdbCoolerSettings-temperature',
  },
  UnitSelectionScreen: {
    // Element id constants for UnitSelection screen
    backgroundImage: 'com.dometicapp:id/unitSelection-backgroundImage',
    scrollView: 'com.dometicapp:id/unitSelection-scrollView',
    englishContainer: 'com.dometicapp:id/unitSelection-englishContainer',
    englishText: 'com.dometicapp:id/unitSelection-englishText',
    iconTickEnglish: 'com.dometicapp:id/unitSelection-iconTickEnglish',
    germanContainer: 'com.dometicapp:id/unitSelection-germanContainer',
    germanText: 'com.dometicapp:id/unitSelection-germanText',
    iconTickGerman: 'com.dometicapp:id/unitSelection-iconTickGerman',
    flatListComponent: 'com.dometicapp:id/unitSelection-flatListComponent',
    flatListItem: 'com.dometicapp:id/unitSelection-flatListItem',
    metric: 'com.dometicapp:id/unitSelection-metric',
    imperial: 'com.dometicapp:id/unitSelection-imperial',
  },
  GuestListScreen: {
    backgroundImage: 'com.dometicapp:id/guestListScreen-backgroundImage',
    scrollView: 'com.dometicapp:id/guestListScreen-scrollview',
    flatList: 'com.dometicapp:id/guestListScreen-flatList',
    flatListItem: 'com.dometicapp:id/guestListScreen-flatListItem',
    deviceImage: 'com.dometicapp:id/guestListScreen-deviceImage',
    pinName: 'com.dometicapp:id/guestListScreen-pinNameText',
    schedulerText: 'com.dometicapp:id/guestListScreen-schedulerText',
    deviceButton: 'com.dometicapp:id/guestListScreen-deviceButton',
    coolerStatus: 'com.dometicapp:id/guestListScreen-coolerStatus',
    saveButtonText: 'com.dometicapp:id/guestListScreen-saveButtonText',
    saveButton: 'com.dometicapp:id/guestListScreen-saveButton',
  },

  EditGuestListScreen: {
    backgroundImage: 'com.dometicapp:id/editGuestListScreen-backgroundImage',
    scrollView: 'com.dometicapp:id/editGuestListScreen-scrollview',
    imageContainer: 'com.dometicapp:id/editGuestListScreen-imageContainer',
    deviceImage: 'com.dometicapp:id/editGuestListScreen-deviceImage',
    pinName: 'com.dometicapp:id/editGuestListScreen-pinNameText',
    schedulerText: 'com.dometicapp:id/editGuestListScreen-schedulerText',
    removeButton: 'com.dometicapp:id/editGuestListScreen-removeButton',
    expandButton: 'com.dometicapp:id/editGuestListScreen-expandButton',
    pinNameValue: 'com.dometicapp:id/editGuestListScreen-pinNameValue',
    pinCodeLabel: 'com.dometicapp:id/editGuestListScreen-pinCodeLabel',
    pinCodeValue: 'com.dometicapp:id/editGuestListScreen-pinCodeValue',
    saveButtonText: 'com.dometicapp:id/editGuestListScreen-saveButtonText',
    saveButton: 'com.dometicapp:id/editGuestListScreen-saveButton',
    flatList: 'com.dometicapp:id/editGuestListScreen-flatList',
    flatListItem: 'com.dometicapp:id/editGuestListScreen-flatListItem',
    addPinButtonImage:
      'com.dometicapp:id/editGuestListScreen-addPinButtonImage',
    addPinButton: 'com.dometicapp:id/editGuestListScreen-addPinButton',
  },
  AddGuestPinScreen: {
    backgroundImage: 'com.dometicapp:id/addGuestPinScreen-backgroundImage',
    scrollView: 'com.dometicapp:id/addGuestPinScreen-scrollview',
    imageContainer: 'com.dometicapp:id/addGuestPinScreen-imageContainer',
    deviceImage: 'com.dometicapp:id/addGuestPinScreen-deviceImage',
    deviceName: 'com.dometicapp:id/addGuestPinScreen-deviceName',
    deviceButton: 'com.dometicapp:id/addGuestPinScreen-deviceButton',
    pinNameLabel: 'com.dometicapp:id/addGuestPinScreen-pinNameLabel',
    pinNameValue: 'com.dometicapp:id/addGuestPinScreen-pinNameValue',
    pinCodeLabel: 'com.dometicapp:id/addGuestPinScreen-pinCodeLabel',
    pinCodeValue: 'com.dometicapp:id/addGuestPinScreen-pinCodeValue',
    saveButtonText: 'com.dometicapp:id/addGuestPinScreen-saveButtonText',
    saveButton: 'com.dometicapp:id/addGuestPinScreen-saveButton',
    flatList: 'com.dometicapp:id/addGuestPinScreen-flatList',
    flatListItem: 'com.dometicapp:id/addGuestPinScreen-flatListItem',
  },
  SDBHomeScreen: {
    backgroundImage: 'com.dometicapp:id/sdbHomeScreen-backgroundImage',
    scrollView: 'com.dometicapp:id/sdbHomeScreen-scrollview',
    imageContainer: 'com.dometicapp:id/sdbHomeScreen-imageContainer',
    sdbFirstSwitch: 'com.dometicapp:id/sdbHomeScreen-sdbFirstSwitch',
    sdbFirstSwitchIcon:
      'com.dometicapp:id/sdbHomeScreen-sdbFirstSwitchLockIcon',
    sdbSecondSwitch: 'com.dometicapp:id/sdbHomeScreen-sdbSecondSwitch',
    sdbSecondSwitchIcon:
      'com.dometicapp:id/sdbHomeScreen-sdbSecondSwitchLockIcon',
    sdbSlider: 'com.dometicapp:id/sdbHomeScreen-slider',
    sdbName: 'com.dometicapp:id/sdbHomeScreen-sdbName',
    sdbSubName: 'com.dometicapp:id/sdbHomeScreen-sdbSubTitle',
    deviceImage: 'com.dometicapp:id/sdbHomeScreen-deviceImage',
    incrementDecrementButton:
      'com.dometicapp:id/sdbHomeScreen-incrementDecrementButton',
    dropdownIcon: 'com.dometicapp:id/sdbHomeScreen-dropdownIcon',
    sliderValueText: 'com.dometicapp:id/sdbHomeScreen-sliderValueText',
    sliderValueLowerext: 'com.dometicapp:id/sdbHomeScreen-sliderValueLowerext',
    sliderValueUpperText:
      'com.dometicapp:id/sdbHomeScreen-sliderValueUpperText',
  },
  MiniBarBasic: {},
  FilterGroupScreen: {
    header: 'com.dometicapp:id/filterGroupScreen-header',
    backgroundImage: 'com.dometicapp:id/filterGroupScreen-backgroundImage',
    manageGroupFlatlist:
      'com.dometicapp:id/filterGroupScreen-manageGroupFlatlist',
    manageGroupFlatListItem:
      'com.dometicapp:id/filterGroupScreen-manageGroupFlatListItem',
  },
  GroupsListScreen: {
    header: 'com.dometicapp:id/groupsListScreen-header',
    backgroundImage: 'com.dometicapp:id/groupsListScreen-backgroundImage',
    groupsFlatList: 'com.dometicapp:id/groupsListScreen-groupsFlatList',
    itemContainer: 'com.dometicapp:id/groupsListScreen-itemContainer',
    deviceName: 'com.dometicapp:id/groupsListScreen-deviceName',
    rightIcon: 'com.dometicapp:id/groupsListScreen- rightIcon',
  },
  EditGroupsScreen: {
    header: 'com.dometicapp:id/editGroupsScreen-header',
    backgroundImage: 'com.dometicapp:id/editGroupsScreen-backgroundImage',
    flatList: 'com.dometicapp:id/editGroupsScreen-flatList',
    removeButton: 'com.dometicapp:id/editGroupsScreen-removeButton',
    deviceImage: 'com.dometicapp:id/editGroupsScreen-deviceImage',
    pinName: 'com.dometicapp:id/editGroupsScreen-pinName',
    schedulerText: 'com.dometicapp:id/editGroupsScreen-schedulerText',
    expandButton: 'com.dometicapp:id/editGroupsScreen-expandButton',
    addPinButton: 'com.dometicapp:id/editGroupsScreen-addPinButton',
    addPinButtonImage: 'com.dometicapp:id/editGroupsScreen-addPinButtonImage',
    deviceName: 'com.dometicapp:id/editGroupsScreen-deviceName',
  },
  EditSubGroupScreen: {
    background: 'com.dometicapp:id/EditSubGroupScreen-background',
    header: 'com.dometicapp:id/EditSubGroupScreen-header',
  },
  CreateUpdateGroupScreen: {
    header: 'com.dometicapp:id/createUpdateGroupScreen-header',
    backgroundImage:
      'com.dometicapp:id/createUpdateGroupScreen-backgroundImage',
    scrollView: 'com.dometicapp:id/createUpdateGroupScreen-scrollView',
    cameraIconContainer:
      'com.dometicapp:id/createUpdateGroupScreen-cameraIconContainer',
    cameraIcon: 'com.dometicapp:id/createUpdateGroupScreen-cameraIcon',
    editGroupFlatList:
      'com.dometicapp:id/createUpdateGroupScreen-editGroupFlatList',
    editGroupFlatListItem:
      'com.dometicapp:id/createUpdateGroupScreen-editGroupFlatListItem',
    NameLabel: 'com.dometicapp:id/createUpdateGroupScreen-NameLabel',
    NameValue: 'com.dometicapp:id/createUpdateGroupScreen-NameValue',
    iconLabel: 'com.dometicapp:id/createUpdateGroupScreen-iconLabel',
    icon: 'com.dometicapp:id/createUpdateGroupScreen-icon',
    saveButton: 'com.dometicapp:id/createUpdateGroupScreen-saveButton',
    saveButtonText: 'com.dometicapp:id/createUpdateGroupScreen-saveButtonText',
    groupIntheDashboardItem:
      'com.dometicapp:id/createUpdateGroupScreen-groupIntheDashboardItem',
  },
  GroupDetailScreen: {
    backgroundImage: 'com.dometicapp:id/groupDetailScreen-backgroundImage',
    scrollView: 'com.dometicapp:id/groupDetailScreen-scrollView',
    editButton: 'com.dometicapp:id/groupDetailScreen-editButton',
    groupName: 'com.dometicapp:id/groupDetailScreen-groupName',
    icon: 'com.dometicapp:id/groupDetailScreen-icon',
    manageSubGroups: 'com.dometicapp:id/groupDetailScreen-manageSubGroups',
    groupIntheDashboardItem:
      'com.dometicapp:id/groupDetailScreen-groupIntheDashboardItem',
    imageContainer: 'com.dometicapp:id/groupDetailScreen-imageContainer',
    deviceImage: 'com.dometicapp:id/groupDetailScreen-deviceImage',
    deviceName: 'com.dometicapp:id/groupDetailScreen-deviceName',
    information: 'com.dometicapp:id/groupDetailScreen-information',
    subGroups: 'com.dometicapp:id/groupDetailScreen-subGroups',
    flatListEdit: 'com.dometicapp:id/groupDetailScreen-flatListEdit',
    flatListEditItem: 'com.dometicapp:id/groupDetailScreen-flatListEditItem',
  },
  GroupsSubGroupsSelection: {
    valueButton: 'com.dometicapp:id/groupDetailScreen-valueButton',
    valueText: 'com.dometicapp:id/groupDetailScreen-valueText',
    iconTick: 'com.dometicapp:id/groupDetailScreen-iconTick',
    header: 'com.dometicapp:id/groupDetailScreen-header',
  },
  CreateUpdateSubGroupScreen: {
    header: 'com.dometicapp:id/CreateUpdateSubGroupScreen-header',
    backgroundImage:
      'com.dometicapp:id/CreateUpdateSubGroupScreen-backgroundImage',
    saveButton: 'com.dometicapp:id/CreateUpdateSubGroupScreen-saveButton',
    saveButtonText:
      'com.dometicapp:id/CreateUpdateSubGroupScreen-saveButtonText',
  },
  SubGroupListScreen: {
    background: 'com.dometicapp:id/SubGroupListScreen-background',
    header: 'com.dometicapp:id/SubGroupListScreen-header',
  },
  ManageGroupedItemsScreen: {
    background: 'com.dometicapp:id/ManageGroupedItemsScreen-background',
    header: 'com.dometicapp:id/ManageGroupedItemsScreen-header',
  },
  ManageSubGroupedItems: {
    background: 'com.dometicapp:id/ManageSubGroupedItems-background',
    header: 'com.dometicapp:id/ManageSubGroupedItems-header',
  },
  ClimateShapeScreen: {
    backgroundImage: 'com.dometicapp:id/ClimateShapeScreen-backgroundImage',
    spinner: 'com.dometicapp:id/ClimateShapeScreen-spinner',
    scrollView: 'com.dometicapp:id/ClimateShapeScreen-scrollView',
    allClimate: 'com.dometicapp:id/ClimateShapeScreen-allClimate',
    power: 'com.dometicapp:id/ClimateShapeScreen-power',
    fanSpeed: 'com.dometicapp:id/ClimateShapeScreen-fanSpeed',
    internalBrightness:
      'com.dometicapp:id/ClimateShapeScreen-internalBrightness',
    climateMode: 'com.dometicapp:id/ClimateShapeScreen-climateMode',
    eco: 'com.dometicapp:id/ClimateShapeScreen-eco',
    powerPercentage: 'com.dometicapp:id/ClimateShapeScreen-powerPercentage',
    quiet: 'com.dometicapp:id/ClimateShapeScreen-quiet',
    scheduler: 'com.dometicapp:id/ClimateShapeScreen-scheduler',
    compressorSpeed: 'com.dometicapp:id/ClimateShapeScreen-compressorSpeed',
    status: 'com.dometicapp:id/ClimateShapeScreen-status',
    temperatureIconRow:
      'com.dometicapp:id/ClimateShapeScreen-temperatureIconRow',
    selectedTimeRow: 'com.dometicapp:id/ClimateShapeScreen-selectedTimeRow',
    humididy: 'com.dometicapp:id/ClimateShapeScreen-humididy',
    pressure: 'com.dometicapp:id/ClimateShapeScreen-pressure',
    editProgram: 'com.dometicapp:id/ClimateShapeScreen-editProgram',
    sleep: 'com.dometicapp:id/ClimateShapeScreen-sleep',
    internalLight: 'com.dometicapp:id/ClimateShapeScreen-internalLight',
    externalLight: 'com.dometicapp:id/ClimateShapeScreen-externalLight',
    dimmer: 'com.dometicapp:id/ClimateShapeScreen-dimmer',
  },
  ClimateMTCScreen: {
    backgroundImage: 'com.dometicapp:id/ClimateShapeScreen-backgroundImage',
    scrollView: 'com.dometicapp:id/ClimateShapeScreen-scrollView',
    allClimate: 'com.dometicapp:id/ClimateShapeScreen-allClimate',
    power: 'com.dometicapp:id/ClimateShapeScreen-power',
    fanSpeed: 'com.dometicapp:id/ClimateShapeScreen-fanSpeed',
    climateMode: 'com.dometicapp:id/ClimateShapeScreen-climateMode',
    eco: 'com.dometicapp:id/ClimateShapeScreen-eco',
    powerPercentage: 'com.dometicapp:id/ClimateShapeScreen-powerPercentage',
    quiet: 'com.dometicapp:id/ClimateShapeScreen-quiet',
    scheduler: 'com.dometicapp:id/ClimateShapeScreen-scheduler',
    compressorSpeed: 'com.dometicapp:id/ClimateShapeScreen-compressorSpeed',
    status: 'com.dometicapp:id/ClimateShapeScreen-status',
    temperatureIconRow:
      'com.dometicapp:id/ClimateShapeScreen-temperatureIconRow',
    selectedTimeRow: 'com.dometicapp:id/ClimateShapeScreen-selectedTimeRow',
    humididy: 'com.dometicapp:id/ClimateShapeScreen-humididy',
    pressure: 'com.dometicapp:id/ClimateShapeScreen-pressure',
    editProgram: 'com.dometicapp:id/ClimateShapeScreen-editProgram',
    temperatureCarousel:
      'com.dometicapp:id/ClimateShapeScreen-temperatureCarousel',
    temperatureCarouselItem:
      'com.dometicapp:id/ClimateShapeScreen-temperatureCarouselItem',
    temperatureInsideText:
      'com.dometicapp:id/ClimateShapeScreen-temperatureInsideText',
    temperatureValueText:
      'com.dometicapp:id/ClimateShapeScreen-temperatureValueText',
    temperatureUnitText:
      'com.dometicapp:id/ClimateShapeScreen-temperatureUnitText',
    fanModeText: 'com.dometicapp:id/ClimateShapeScreen-fanModeText',
    fanModeIcon: 'com.dometicapp:id/ClimateShapeScreen-fanModeIcon',
    climateIconContainer: 'com.dometicapp:id/ClimateShapeScreen-iconContainer',
    climateModeIcon: 'climateModeIcon',
    ecoIcon: 'ecoIcon',
    schdulerIcon: 'schdulerIcon',
    quietIcon: 'quietIcon',
    climateZone: 'com.dometicapp:id/ClimateShapeScreen-zone',
    climatePrograms: 'com.dometicapp:id/ClimateShapeScreen-programs',
    editProgramSaveButton:
      'com.dometicapp:id/ClimateShapeScreen-editProgramSaveButton',
  },
  FloorScreen: {
    header: 'com.dometicapp:id/FloorScreen-header',
    backgroundImage: 'com.dometicapp:id/FloorScreen-backgroundImage',
    scrollView: 'com.dometicapp:id/FloorScreen-scrollView',
    flatlistRow: 'com.dometicapp:id/FloorScreen-flatlistRow',
    flatlist: 'com.dometicapp:id/FloorScreen-flatlist',
    floorName: 'com.dometicapp:id/FloorScreen-floorName',
    roomCount: 'com.dometicapp:id/FloorScreen-roomCount',
    expandIcon: 'com.dometicapp:id/FloorScreen-expandIcon',
  },
  RoomScreen: {
    backgroundImage: 'com.dometicapp:id/RoomScreen-backgroundImage',
    header: 'com.dometicapp:id/RoomScreen-header',
    scrollView: 'com.dometicapp:id/RoomScreen-scrollView',
    flatlistRow: 'com.dometicapp:id/RoomScreen-flatlistRow',
    flatlist: 'com.dometicapp:id/RoomScreen-flatlist',
    roomIcon: 'com.dometicapp:id/RoomScreen-roomIcon',
    roomName: 'com.dometicapp:id/RoomScreen-roomName',
    addEditText: 'com.dometicapp:id/RoomScreen-addEditText',
    expandIcon: 'com.dometicapp:id/RoomScreen-expandIcon',
    bleIcon: 'com.dometicapp:id/RoomScreen-bleIcon',
    wifiIcon: 'com.dometicapp:id/RoomScreen-wifiIcon',
    refreshIcon: 'com.dometicapp:id/RoomScreen-refreshIcon',
    warnIcon: 'com.dometicapp:id/RoomScreen-warnIcon',
  },
  BLEInstructions: {
    header: 'com.dometicapp:id/BLEInstructions-header',
    backgroundImage: 'com.dometicapp:id/BLEInstructions-backgroundImage',
    instructionText: 'com.dometicapp:id/BLEInstructions-instructionText',
    saveButton: 'com.dometicapp:id/BLEInstructions-saveButton',
  },
  AreaLights: {
    header: 'com.dometicapp:id/arealights-header',
    backgroundImage: 'com.dometicapp:id/arealights-backgroundImage',
    schedulerFromText: 'com.dometicapp:id/arealights-schedulerFromText',
    schedulerToggleButton: 'com.dometicapp:id/arealights-schedulerToggleButton',
    schedulerStartTimer: 'com.dometicapp:id/arealights-schedulerStartTimer',
    schedulerEndTimer: 'com.dometicapp:id/arealights-schedulerEndTimer',
    schedulerToText: 'com.dometicapp:id/arealights-schedulerToText',
    batteryText: 'com.dometicapp:id/arealights-batteryText',
    schedulerIcon: 'com.dometicapp:id/arealights-schedulerIcon',
    schedulerIconOffState: 'com.dometicapp:id/arealights-schedulerIconOffState',
    batteryIcon: 'com.dometicapp:id/arealights-batteryIcon',
    batteryIconOffState: 'com.dometicapp:id/arealights-batteryIconOffState',
    colorPickerLightButton:
      'com.dometicapp:id/arealights-colorPickerLightButton',
    colorSceneButton: 'com.dometicapp:id/arealights-colorSceneButton',
    warmSceneButton: 'com.dometicapp:id/arealights-warmSceneButton',
    sceneButton: 'com.dometicapp:id/arealights-sceneButton',
    colorSceneButtonOffIcon:
      'com.dometicapp:id/arealights-colorSceneButtonOffIcon',
    colorSceneButtonOnIcon:
      'com.dometicapp:id/arealights-colorSceneButtonOnIcon',
    warmSceneButtonOnIcon: 'com.dometicapp:id/arealights-warmSceneButtonOnIcon',
    warmSceneButtonOffIcon:
      'com.dometicapp:id/arealights-warmSceneButtonOffIcon',
    sceneButtonOnIcon: 'com.dometicapp:id/arealights-sceneButtonOnIcon',
    sceneButtonOffIcon: 'com.dometicapp:id/arealights-sceneButtonOffIcon',
    bugLightButton: 'com.dometicapp:id/arealights-bugLightButton',
    bugLightIcon: 'com.dometicapp:id/arealights-bugLightIcon',
    candleLightButton: 'com.dometicapp:id/arealights-candleLightButton',
    readingLightButton: 'com.dometicapp:id/arealights-readingLightButton',
    nightLightButton: 'com.dometicapp:id/arealights-nightLightButton',
    chargingLightButton: 'com.dometicapp:id/arealights-chargingLightButton',
    musicLightButton: 'com.dometicapp:id/arealights-musicLightButton',
    colorPowerButton: 'com.dometicapp:id/arealights-colorPowerButton',
    colorPowerOnIcon: 'com.dometicapp:id/arealights-colorPowerOnIcon',
    colorPowerOffIcon: 'com.dometicapp:id/arealights-colorPowerOffIcon',
    warmPowerButton: 'com.dometicapp:id/arealights-warmPowerButton',
    warmPowerOnIcon: 'com.dometicapp:id/arealights-warmPowerOnIcon',
    warmPowerOffIcon: 'com.dometicapp:id/arealights-warmPowerOffIcon',
    scenePowerButton: 'com.dometicapp:id/arealights-scenePowerButton',
    scenePowerOnIcon: 'com.dometicapp:id/arealights-scenePowerOnIcon',
    scenePowerOffIcon: 'com.dometicapp:id/arealights-scenePowerOffIcon',
    sceneContainer: 'com.dometicapp:id/arealights-sceneContainer',
    sceneBrightnessSlider: 'com.dometicapp:id/arealights-sceneBrightnessSlider',
    colorBrightnessSlider: 'com.dometicapp:id/arealights-colorBrightnessSlider',
    colorrainbowSlider: 'com.dometicapp:id/arealights-rainbowColorSlider',
    warmBrightnessSlider: 'com.dometicapp:id/arealights-warmBrightnessSlider',
    warmColorSlider: 'com.dometicapp:id/arealights-warmColorSlider',
    settingNameLabel: 'com.dometicapp:id/arealights-settingNameLabel',
    settingEditButton: 'com.dometicapp:id/arealights-settingEditButton',
    settingProductInformation:
      'com.dometicapp:id/arealights-settingProductInformation',
    settingNotification: 'com.dometicapp:id/arealights-settingNotification',
    settingAdvanced: 'com.dometicapp:id/arealights-settingAdvanced',
    settingAbout: 'com.dometicapp:id/arealights-settingAbout',
    areaLightNameLabel: 'com.dometicapp:id/arealights-areaLightNameLabel',
    areaLightNameValue: 'com.dometicapp:id/arealights-areaLightNameValue',
    saveButton: 'com.dometicapp:id/arealights-areaLightSaveButton',
    saveButtonText: 'com.dometicapp:id/arealights-areaLightSaveButtonText',
  },

  // Sensor UI related ElementID constants
  MainDoorSensorEdit: {
    header: 'com.dometicapp:id/MainDoorSensorEdit-header',
    backgroundImage: 'com.dometicapp:id/MainDoorSensorEdit-backgroundImage',
    scrollView: 'com.dometicapp:id/MainDoorSensorEdit-scrollview',
    nameLabel: 'com.dometicapp:id/MainDoorSensorEdit-nameLabel',
    nameValue: 'com.dometicapp:id/MainDoorSensorEdit-nameValue',
    zoneNumberLabel: 'com.dometicapp:id/MainDoorSensorEdit-zoneNumberLabel',
    zoneNumberValue: 'com.dometicapp:id/MainDoorSensorEdit-zoneNumberValue',
    saveButton: 'com.dometicapp:id/MainDoorSensorEdit-saveButton',
    saveButtonText: 'com.dometicapp:id/MainDoorSensorEdit-saveButtonText',
    bluetoothLabel: 'com.dometicapp:id/MainDoorSensorEdit-bluetoothLabel',
    bluetoothSwitch: 'com.dometicapp:id/MainDoorSensorEdit-bluetoothSwitch',
    alertLatencyLabel: 'com.dometicapp:id/MainDoorSensorEdit-alertLatencyLabel',
    alertLatencyValue: 'com.dometicapp:id/MainDoorSensorEdit-alertLatencyValue',
    alertLatencyIcon: 'com.dometicapp:id/MainDoorSensorEdit-alertLatencyIcon',
  },
  EditDometicLPGTankSensorScreen: {
    header: 'com.dometicapp:id/EditDometicLPGTankSensorScreen-header',
    backgroundImage:
      'com.dometicapp:id/EditDometicLPGTankSensorScreen-backgroundImage',
    scrollView: 'com.dometicapp:id/EditDometicLPGTankSensorScreen-scrollview',
    saveButton: 'com.dometicapp:id/EditDometicLPGTankSensorScreen-saveButton',
    saveButtonText:
      'com.dometicapp:id/EditDometicLPGTankSensorScreen-saveButtonText',
    nameLabel: 'com.dometicapp:id/EditDometicLPGTankSensorScreen-nameLabel',
    nameText: 'com.dometicapp:id/EditDometicLPGTankSensorScreen-nameText',
    regionLabel: 'com.dometicapp:id/EditDometicLPGTankSensorScreen-regionLabel',
    regionText: 'com.dometicapp:id/EditDometicLPGTankSensorScreen-regionText',
    regionIcon: 'com.dometicapp:id/EditDometicLPGTankSensorScreen-regionIcon',
    tankSizeLabel:
      'com.dometicapp:id/EditDometicLPGTankSensorScreen-tankSizeLabel',
    tankSizeText:
      'com.dometicapp:id/EditDometicLPGTankSensorScreen-tankSizeText',
    tankSizeIcon:
      'com.dometicapp:id/EditDometicLPGTankSensorScreen-tankSizeIcon',
    tankLevelUnitLabel:
      'com.dometicapp:id/EditDometicLPGTankSensorScreen-tankLevelUnitLabel',
    tankLevelUnitText:
      'com.dometicapp:id/EditDometicLPGTankSensorScreen-tankLevelUnitText',
    tankLevelUnitIcon:
      'com.dometicapp:id/EditDometicLPGTankSensorScreen-tankLevelUnitIcon',
    bluetoothLabel:
      'com.dometicapp:id/EditDometicLPGTankSensorScreen-bluetoothLabel',
    bluetoothText:
      'com.dometicapp:id/EditDometicLPGTankSensorScreen-bluetoothText',
    bluetoothIcon:
      'com.dometicapp:id/EditDometicLPGTankSensorScreen-bluetoothIcon',
    alertThresholdLabel:
      'com.dometicapp:id/EditDometicLPGTankSensorScreen-alertThresholdLabel',
    alertThresholdText:
      'com.dometicapp:id/EditDometicLPGTankSensorScreen-alertThresholdText',
    alertThresholdIcon:
      'com.dometicapp:id/EditDometicLPGTankSensorScreen-alertThresholdIcon',
    alertLatencyLabel:
      'com.dometicapp:id/EditDometicLPGTankSensorScreen-alertLatencyLabel',
    alertLatencyText:
      'com.dometicapp:id/EditDometicLPGTankSensorScreen-alertLatencyText',
    alertLatencyIcon:
      'com.dometicapp:id/EditDometicLPGTankSensorScreen-alertLatencyIcon',
  },
  EditClimateSensorScreen: {
    header: 'com.dometicapp:id/EditClimateSensorScreen-header',
    backgroundImage:
      'com.dometicapp:id/EditClimateSensorScreen-backgroundImage',
    scrollView: 'com.dometicapp:id/EditClimateSensorScreen-scrollview',
    saveButton: 'com.dometicapp:id/EditClimateSensorScreen-saveButton',
    saveButtonText: 'com.dometicapp:id/EditClimateSensorScreen-saveButtonText',
    bluetoothToggle:
      'com.dometicapp:id/EditClimateSensorScreen-bluetoothToggle',
    bluetoothText: 'com.dometicapp:id/EditClimateSensorScreen-bluetoothText',
    powerToggle: 'com.dometicapp:id/EditClimateSensorScreen-powerToggle',
    zoneNumberValue:
      'com.dometicapp:id/EditClimateSensorScreen-zoneNumberValue',
    zoneNumberLabel:
      'com.dometicapp:id/EditClimateSensorScreen-zoneNumberLabel',
    nameValue: 'com.dometicapp:id/EditClimateSensorScreen-nameValue',
    nameLabel: 'com.dometicapp:id/EditClimateSensorScreen-nameLabel',
  },
};
export default elementIdConstants;
